### ISSUE TITLE
Add documentation on how to leverage AdGuard to your clients

### ISSUE THREAD

**Issue by frenck** [hassio-addons/addon-tailscale#10]
# Problem/Motivation

This add-on can be used in conjunction with e.g., the AdGuard add-on. Ads filtering on the go (even without using exit node features).

This needs to be documented.

**Comment by ronaldheft** [comment]
Just gave this a go by adding the IP address Tailscale assigns to Home Assistant as a DNS option in the Tailscale interface. No go, so I assume there is an added step or two.
