### ISSUE TITLE
Error Attempting to Login

### ISSUE THREAD

**Issue by LordNex** [hassio-addons/addon-tailscale#103]
After I start tailscale and goto login through the UI I get the following error

Failed to log in: null is not an
obiect (evaluating
'window.open (url,
1
blank").focus")

Any idea?

**Comment by LordNex** [comment]
![image](https://user-images.githubusercontent.com/9270948/175759511-793b569d-e899-4cd9-bb00-f0d7535b763c.jpeg)

**Comment by tjorim** [comment]
Looks like you are using iOS, open it on your pc and should be fine.

**Comment by LordNex** [comment]
> Looks like you are using iOS, open it on your pc and should be fine.

Yes I am doing it on iOS. But I've tried several different browsers you would think it would work with one of them. I'll give it a try but that might be something you want to look into as a lot of people are going to just use the iOS HA app
