### ISSUE TITLE
--adveritse-routes and --advertise-exit-node configuration flags should be optional

### ISSUE THREAD

**Issue by kurtlieber** [hassio-addons/addon-tailscale#119]
Currently, the tailscale addon hard codes the --advertise-routes=<local subnet> into the command that starts tailscale.  For networks that already have a different tailscale node handling subnet routing duties, this throws errors in the tailscale web interface.

Please make this config flag optional or provide some other supported means of disabling it.

Similarly, --advertise-exit-node should also be configurable as not everyone wants to use exit nodes in the first place and/or they may already have an exit node in place.  Note:  this option can be disabled by going to the tailscale web UI at http://homeassistant.local:25899/ but it would still be nice to not have to disable it every time the addon restarts.

**Comment by Yeradon** [comment]
I think routing functionality of tailscale is always double opt-in. Meaning the client has to advertise its capabilities, but you have to enable them explicitly in the tailscale admin console. And the exit node has to be selected on each client aswell (default is none).

**Comment by kurtlieber** [comment]
Re: having to enable them in the tailscale admin console: yes, that's accurate.  However, if you already have a subnet router set up for that particular subnet, the admin console throws errors about the HA tailscale subnet advertisement being "unapproved routes".  Additionally, by advertising itself as a subnet router, the HA tailscale instance will also act as a failover router (this is by design for tailscale) which may not be desirable.

IMO this feature should not be even advertised unless specifically configured to do so.

On the exit node, that is not accurate.  As currently designed, the HA tailscale addon installs itself as an active exit node.  You can choose to go into the tailscale web UI on the node and disable that functionality, but that is an extra step.  This should NOT be enabled by default as people may not want all their internet traffic from all their tailscale-enabled devices running through their Home Assistant machine.

**Comment by Mincka** [comment]
In the past, I used this alternative addon for tailscale, when this one was broken.
https://github.com/tsujamin/hass-addons/tree/main/tailscale

It offers a more recent version and a lot more possibilities regarding the options, especially route advertising.

Route advertisement and exit node are opt-in options in @tsujamin's addon.

Since I need both, my config looks like this in YAML and multiple routes support is working great.

```
hostname: homeassistant
auth_key: tskey-auth-xxx
advertise_routes: 10.0.0.0/24,192.168.0.0/24
userspace_networking: true
advertise_exit_node: true
accept_routes: true
```

In your case, since you do not want both options to be enabled, it's even easier to setup, just don't check them.

**Comment by kurtlieber** [comment]
This remains an issue and should not be marked stale.

**Comment by kurtlieber** [comment]
Bump to keep the bot happy, even though it appears this addon has been abandoned.
