### ISSUE TITLE
Documentation should note that the addon starts a web interface for tailscale

### ISSUE THREAD

**Issue by kurtlieber** [hassio-addons/addon-tailscale#120]
I am not github savvy enough to know how to do a pull request - apologies for not making this easier.

That said, when I was digging around the docker configuration options, I noticed that the addon spins up an optional tailscale web interface for configuring the client:

http://homeassistant.local:25899/

The documentation should be updated to reflect this.  My suggestion is to update the "Configuration" section of DOCS.md to reflect this.  I've created a simple patch file with my suggestions.

[docs-patch.txt](https://github.com/hassio-addons/addon-tailscale/files/9854388/docs-patch.txt)

(It also may make sense to make this option configurable as well - I can see how some folks might not want this enabled on their system)

**Comment by tjorim** [comment]
From the docs: Open the Web UI of the "Tailscale" add-on to complete authentication and couple your Home Assistant instance with your Tailscale account. Note: Some browsers don't work with this step. It is recommended to complete this step on a desktop or laptop computer using the Chrome browser.

**Comment by tjorim** [comment]
So the OPEN WEB UI button does exactly that (or you can access it from the sidebar).

**Comment by kurtlieber** [comment]
Fair enough - I can see the confusion.  From my standpoint, "WebUI" is different than "totally separate web server, running on a different port".  "WebUI" could simply be a page built into HA, whereas a separate web server has security considerations, firewall considerations, patching considerations, etc.

I would still suggest making it more overt and transparent in the documentation - I don't think doing so really hurts anything.

**Comment by elcajon** [comment]
> Fair enough - I can see the confusion. From my standpoint, "WebUI" is different than "totally separate web server, running on a different port". "WebUI" could simply be a page built into HA, whereas a separate web server has security considerations, firewall considerations, patching considerations, etc.

The HA ingress function (technically Nginx in proxy mode) makes sure that only the HA docker network is able to access this ingress page, I am not sure how you set up your HA instance but the Tailscale page shouldn't be accessible on port 25899 (as the port is bind to 127.0.0.1)

**Comment by kurtlieber** [comment]
> the Tailscale page shouldn't be accessible on port 25899 

It absolutely is available, both via the local LAN IP as well as the tailscale IP and magicDNS name.

I'm using the vanilla HomeAssistant OS runing as a KVM VM, along with this tailscale add-on.  I didn't muck with any of the networking.   This happens on both of the HAOS instances that I use.

If the intended functionality is to have it only bound to localhost, then that appears to be a bug.

**Comment by elcajon** [comment]
I am running HA OS as Proxmox VM (amd64). I've tried to reproduce the issue but I am not able to access the port locally. 

Just took a look at netstat inside the VM, binding looks also correct.

<img width="1098" alt="image" src="https://user-images.githubusercontent.com/52052494/200650784-b6d5e72a-374e-4694-aaf9-9116919a069d.png">


This is the corresponding add-on service definition, providing the Tailscale web ui
https://github.com/hassio-addons/addon-tailscale/blob/6be6bff0fb894fd9f8adc441663c086c0ba4f4b6/tailscale/rootfs/etc/services.d/web/run#L1-L15

**Comment by kurtlieber** [comment]
I've set up two different instances of HA on KVM, running on Rocky Linux 9 (RHEL 9 clone).  Both times, the Tailscale instance was exposed via the external IP.   Also, my netstat looks similar to yours:

![Screenshot from 2022-11-10 06-48-26](https://user-images.githubusercontent.com/3666535/201112349-28072e9b-ec5f-4631-90af-7d756a246b87.png)

And yet I'm still able to access the interface through the tailscale IP:

![Screenshot from 2022-11-10 06-49-44](https://user-images.githubusercontent.com/3666535/201112458-92781780-8136-48d5-bdca-c6fa4273f713.png)

Now, I will say something seems to have changed with the most recent HAOS update, as now I can no longer access the interface from the regular external IP, where I know that was working before.  However, the tailscale interface is still absolutely working.

My KVM environment is set up to  use bridged networking (not NAT), to allow direct LAN access to the VMs. I don't think that would make a difference, but calling it out in case it does.

**Comment by kurtlieber** [comment]
Issue still persists.  Posting to avoid having the bot close.

**Comment by kurtlieber** [comment]
Bump to keep the bot happy, even though it appears this addon has been abandoned.
