### ISSUE TITLE
iOS App authorization

### ISSUE THREAD

**Issue by LEJOUI** [hassio-addons/addon-tailscale#13]
# Problem/Motivation

Authorization tailscale not possible in the HA iOS companion app. Authorization happens in a pop-up which doesn’t seem to work in the app.
## Expected behavior
Opening a pop-up in safari where you can authorize.

## Actual behavior

Error

![88376835-1BC2-4489-B737-1D35462DF873](https://user-images.githubusercontent.com/13658422/130281287-9ee1cac0-76ff-473b-8be2-e8dbc25cf4d5.png)

## Steps to reproduce

Install the add-on and first setup in the app.

## Proposed changes

Not sure if it’s possible to authorize in the app, otherwise some documentation to not authorize in the app would be needed.

**Comment by frenck** [comment]
Unfixable, please use a desktop computer.
