### ISSUE TITLE
Is this going to get updated to the newest version.

### ISSUE THREAD

**Issue by DezzyMelb** [hassio-addons/addon-tailscale#141]
# Problem/Motivation

Version is out dated

## Expected behavior

More stable and less Sec Vulnerabilities

## Actual behavior

Old version

## Steps to reproduce

Install Addon

## Proposed changes

Upgrade to newest linux version.

**Comment by lmagyar** [comment]
There is a PR #133 waiting for approval... I regularly push commits when I upgrade my fork...

**Comment by Loweack** [comment]
Thank you @lmagyar!

**Comment by lmagyar** [comment]
You can test all the PR-s in my fork at: https://github.com/lmagyar/homeassistant-addon-tailscale

And there is an additional alpha feature in my other fork: https://github.com/lmagyar/homeassistant-addon-tailscale-funnel (funnel is a TCP proxy (internet->VPN) at Tailscale to access your devices through your VPN from the internet, without installing a VPN client on your client device (eg. phone) - it is in alpha phase at Tailscale, so I put it in another repo, though it only emits some info messages in the log when you don't configure funnel, so basically you can test is directly I think)

**Comment by frenck** [comment]
done in #152
