### ISSUE TITLE
Enable Tailscale SSH access?

### ISSUE THREAD

**Issue by magnolia61** [hassio-addons/addon-tailscale#143]
# Problem/Motivation

I would like to use Tailscale SSH access

## Expected behavior

Tailscale SSH access is possible :-)

## Actual behavior

Tailscale SSH does not seem to be possible with this add-on

## Proposed changes

It would be nice though if through the yaml ssh access could be activated.

(Also I cannot seem to activate it through the terminal with )tailscale up --ssh

**Comment by lmagyar** [comment]
I've implemented this in my [fork](https://github.com/lmagyar/homeassistant-addon-tailscale-funnel) to test it, though you will gain access only to the tailscale add-on's container, not the ssh add-on's cli, so it doesn't seems to be too useful. Or do you really need ssh access to the tailscale add-on?

**Comment by frenck** [comment]
Sorry, there is really no use in implementing it.

Going to close it on this end.

../Frenck
