### ISSUE TITLE
Custom login server

### ISSUE THREAD

**Issue by reeseovine** [hassio-addons/addon-tailscale#144]
# Problem/Motivation

I would like to join my HAOS VM to my tailnet that is managed by [Headscale](https://github.com/juanfont/headscale). This use case is [officially supported](https://tailscale.com/opensource/#encouraging-headscale) by Tailscale, and the command to join it is:

```sh
sudo tailscale up --login-server https://headscale.example.com
```

## Expected behavior

I hoped there would be an option to specify a login server other than the default one.

## Actual behavior

This option is missing and the addon only seems to support the default coordination server.

## Steps to reproduce

1. install and start the addon
2. open web UI
3. see Tailscale login page

## Proposed changes

There should be an optional config setting (much like ACL tags) for a custom login server. It would only add an extra step for Headscale users, and no extra work for users of Tailscale's coordination server.

**Comment by tylervick** [comment]
I'd also appreciate this feature. FWIW there are alternative addons that support this [1] but I'd prefer to use this one.

This may also require some changes to the auth flow, since headscale instances don't provide the same login UX. A simple solution would be supporting a pre-generated auth key.

**Comment by frenck** [comment]
Closing this, as it is an feature request and not an issue.

../Frenck
