### ISSUE TITLE
iOS native app currently incompatible with target=_blank links

### ISSUE THREAD

**Issue by bitfliq** [hassio-addons/addon-tailscale#157]
# Problem/Motivation

iOS native app currently does not support target=_blank in window.open.  This may also be an problem for native Safari browsing.
![before](https://user-images.githubusercontent.com/6220097/227745726-95a221e1-db39-4c81-a938-42def2b899cf.jpeg)

## Related Issues
https://github.com/hassio-addons/addon-tailscale/issues/103
https://github.com/home-assistant/iOS/discussions/2325

## Expected behavior

Native app open url dialog is triggered or link is provided for user.

## Actual behavior

Modal popup, "Failed to log in: null is not an object (evaluating 'window.open(url,"_blank").focus') (OK)

Previously referenced here:
https://github.com/hassio-addons/addon-tailscale/issues/103

## Steps to reproduce

Install Tailscale addon.  Attempt to authenticate in to tailscale from iOS mobile app or mobile Safari. 

## Proposed changes

Modify JS to provide fallback.  https://github.com/bitfliq/addon-tailscale/tree/main/tailscale
Desktop browser UX is unchanged.  Fallback for mobile is this:
![after](https://user-images.githubusercontent.com/6220097/227745720-7f74c649-f0ec-4cf5-aa40-e590143cc246.jpeg)

**Comment by sinclairpaul** [comment]
Why wouldn't we just wait for the issue to be fixed upstream, rather than implementing a workaround that has to be removed in the future?, not sure of the benefit here.

**Comment by bitfliq** [comment]
By upstream do you mean the tailscale addon?  My proposed change there is only a workaround - any other addons that have similar JavaScript behavior elsewhere will demonstrate the same problem.

**Comment by bitfliq** [comment]
(Previous comment deleted - Sorry @sinclairpaul! I was confused in replying to your message and thought this was the discussion thread I started for the iOS client. )

Yes, this would hopefully eventually be mitigated in the iOS client.  This issue also happens for standalone mobile Safari, at least if HA is accessed over http.  The addon already has one workaround for loading the tailscale auth website on desktop.
