### ISSUE TITLE
Tailscale Funnels Support

### ISSUE THREAD

**Issue by leoherzog** [hassio-addons/addon-tailscale#166]
# Problem/Motivation

Tailscale Funnels have graduated from Alpha to Beta, and are an awesome way to get a Home Assistant instance on the public internet without paying for Casa.

https://tailscale.com/blog/tailscale-funnel-beta/

## Expected behavior

I could SSH in and somehow run
```shell
$ tailscale serve https / http://localhost:3000
$ tailscale funnel 443 on
```
in the addon's Docker container.

## Actual behavior

I'm on Home Assistant OS with no access to the `tailscale` command when SSH'd in.

## Steps to reproduce

1. Install Home Assistant OS
2. Install this add-on
3. Attempt to enable Funnel

## Proposed changes

Expose this option via the web interface, perhaps? Or have some smart defaults that would enable this, similar to how you handle [Taildrop](https://github.com/hassio-addons/addon-tailscale/blob/main/tailscale/DOCS.md#taildrop)

**Comment by frenck** [comment]
Closing this, as it is a feature request and not an issue.

../Frenck

**Comment by leoherzog** [comment]
Okay. Do you have somewhere where feature requests are collected?
