### ISSUE TITLE
Add option to not advertise as subnet router

### ISSUE THREAD

**Issue by celeroncool** [hassio-addons/addon-tailscale#167]
# Problem/Motivation

I already have a subnet router (pfSense firewall), and would like to not advertise my HomeAssistant as subnet router.

## Expected behavior

Option to not advertise as subnet router, same as the option to not advertise as exit node.

## Actual behavior

By default, addon configures itself as subnet router. I have to make sure that I do not allow HomeAssistant as subnet router in tailscale dashboard.

## Steps to reproduce

Install Addon
Login
Go to tailscale dashboard (https://login.tailscale.com/admin/machines)
Check HomeAssistant machine -> Edit route settings -> Subnet routes

## Proposed changes

Add button to not advertise as subnet router.

**Comment by frenck** [comment]
Closing, as this is not an issue, but a feature request.

../Frenck
