### ISSUE TITLE
Headscale support

### ISSUE THREAD

**Issue by bugybq** [hassio-addons/addon-tailscale#176]
# Problem/Motivation
possible support for using selfhosted headscale server

## Expected behavior
tailscale linux client supports customized login server natively. Is it possible to supply login-server parameter via tailscale add-on? So that selfhosted headscale server could be used.
```
tailscale up --login-server YOUR_HEADSCALE_URL
```
reference  [tailscale CLI docuemt - login](https://tailscale.com/kb/1080/cli/?tab=linux#login)。

**Comment by lmagyar** [comment]
See: #175
