### ISSUE TITLE
Failure to login to Tailscale via add on web

### ISSUE THREAD

**Issue by Skyman64** [hassio-addons/addon-tailscale#190]
# Problem/Motivation
You cannot configure and connect the Tailscale add-on to the Tailscale network after installation

## Expected behavior
When clicking on the webui button and connecting through to the Tailscale login page, you should be able to press the login button and connect to the Tailscale system

## Actual behavior
The system responds with "Failed operation: null is not an object (evaluating 'window.open(url, "_blank").focus')" and cannot connect in any further

## Steps to reproduce
Install the Tailscale add-on on a raspberry pi (4) running HA OS. Start the add-on and connect to the webui. Then press the button to log in to the Tailscale network.

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
What do you use to click on that button?

**Comment by Skyman64** [comment]
I am on a Mac and was using safari. The same thing happens in the HA application on the Mac, and the HA application on the iPad, safari on the iPad, and Duck Duck Go on the iPad.

**Comment by frenck** [comment]
Reading the docs might have helped in this case:

![image](https://user-images.githubusercontent.com/195327/233802577-30ceb3f0-b43e-4243-9559-6e327d7e0039.png)

../Frenck

**Comment by Skyman64** [comment]
I saw that but to be honest I don't have chrome installed. I did just try it with Edge and that works on MacOS

**Comment by frenck** [comment]
Edge = Chrome.

**Comment by Skyman64** [comment]
BTW - I know it's not the place, but thank you for your fast response and what you have done for the HA project.
