### ISSUE TITLE
login-server doesnt work

### ISSUE THREAD

**Issue by fattylewis** [hassio-addons/addon-tailscale#193]
# Problem/Motivation

Ive been trying to connect to my headscale server.

## Expected behavior

I'd expect to be asked to login to my headscale server

## Actual behavior

tailscale attempts to start, but it looks like the command-line flag is just set incorrectly. 
Its trying to set:

`-login_server`
Instead of (i believe)
`--login-server`

## Steps to reproduce

Install Addon, try setting a login-server (shouldnt really matter what you set, as its the command line flag that fails.)
If you would like a proper server to test against, email me at jon@(my username here).com and i can send you mine.

## Proposed changes

Change the command-line flag to --login-server.

**Comment by fattylewis** [comment]
`2023/04/28 10:16:22 got LocalBackend in 7ms
2023/04/28 10:16:22 Start
2023/04/28 10:16:22 Backend: logs: be:81e0c7cf81e4f1b4635445a10da594f61068f11d9f75037a8b96450d218856bd fe:
2023/04/28 10:16:22 Switching ipn state NoState -> NeedsLogin (WantRunning=false, nm=false)
2023/04/28 10:16:22 blockEngineUpdates(true)
2023/04/28 10:16:22 health("overall"): error: state=NeedsLogin, wantRunning=false
2023/04/28 10:16:22 wgengine: Reconfig: configuring userspace WireGuard config (with 0/0 peers)
2023/04/28 10:16:22 wgengine: Reconfig: configuring router
2023/04/28 10:16:22 wgengine: Reconfig: configuring DNS
2023/04/28 10:16:22 dns: Set: {DefaultResolvers:[] Routes:{} SearchDomains:[] Hosts:0}
2023/04/28 10:16:22 dns: Resolvercfg: {Routes:{} Hosts:0 LocalDomains:[]}
s6-rc: info: service init-nginx successfully started
s6-rc: info: service nginx: starting
s6-rc: info: service nginx successfully started
[10:16:22] INFO: Starting NGinx...
flag provided but not defined: -login_server
USAGE
  up [flags]
"tailscale up" connects this machine to your Tailscale network,
triggering authentication if necessary.
With no flags, "tailscale up" brings the network online without
changing any settings. (That is, it's the opposite of "tailscale
down").
If flags are specified, the flags must be the complete set of desired
settings. An error is returned if any setting would be changed as a
result of an unspecified flag's default value, unless the --reset flag
is also used. (The flags --auth-key, --force-reauth, and --qr are not
considered settings that need to be re-specified when modifying
settings.)
FLAGS
  --accept-dns, --accept-dns=false
    	accept DNS configuration from the admin panel (default true)
  --accept-risk string
    	accept risk and skip confirmation for risk types: lose-ssh,all
  --accept-routes, --accept-routes=false
    	accept routes advertised by other Tailscale nodes (default false)
  --advertise-exit-node, --advertise-exit-node=false
    	offer to be an exit node for internet traffic for the tailnet (default false)
  --advertise-routes string
    	routes to advertise to other nodes (comma-separated, e.g. "10.0.0.0/8,192.168.0.0/24") or empty string to not advertise routes
  --advertise-tags string
    	comma-separated ACL tags to request; each must start with "tag:" (e.g. "tag:eng,tag:montreal,tag:ssh")
  --auth-key string
    	node authorization key; if it begins with "file:", then it's a path to a file containing the authkey
  --exit-node string
    	Tailscale exit node (IP or base name) for internet traffic, or empty string to not use an exit node
  --exit-node-allow-lan-access, --exit-node-allow-lan-access=false
    	Allow direct access to the local network when routing traffic via an exit node (default false)
  --force-reauth, --force-reauth=false
    	force reauthentication (default false)
  --hostname string
    	hostname to use instead of the one provided by the OS
  --json, --json=false
    	output in JSON format (WARNING: format subject to change) (default false)
  --login-server string
    	base URL of control server (default https://controlplane.tailscale.com)
  --netfilter-mode string
    	netfilter mode (one of on, nodivert, off) (default on)
  --operator string
    	Unix username to allow to operate on tailscaled without sudo
  --qr, --qr=false
    	show QR code for login URLs (default false)
  --reset, --reset=false
    	reset unspecified settings to their default values (default false)
  --shields-up, --shields-up=false
    	don't allow incoming connections (default false)
  --snat-subnet-routes, --snat-subnet-routes=false
    	source NAT traffic to local routes advertised with --advertise-routes (default true)
  --ssh, --ssh=false
    	run an SSH server, permitting access per tailnet admin's declared policy (default false)
  --timeout duration
    	maximum amount of time to wait for tailscaled to enter a Running state; default (0s) blocks forever (default 0s)
s6-rc: warning: unable to start service post-tailscaled: command exited 2
/run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.
/run/s6/basedir/scripts/rc.init: fatal: stopping the container.
s6-rc: info: service tailscaled: stopping
s6-rc: info: service nginx: stopping
[10:16:22] INFO: Service tailscaled exited with code 256 (by signal 15)
s6-rc: info: service tailscaled successfully stopped
[10:16:22] INFO: Service NGINX exited with code 0 (by signal 0)
s6-rc: info: service nginx successfully stopped
s6-rc: info: service init-nginx: stopping
s6-rc: info: service web: stopping
s6-rc: info: service init-nginx successfully stopped
[10:16:22] INFO: Service Tailscale web exited with code 256 (by signal 15)
s6-rc: info: service web successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service base-addon-log-level: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service base-addon-log-level successfully stopped
s6-rc: info: service base-addon-banner: stopping
s6-rc: info: service base-addon-banner successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped`

**Comment by fattylewis** [comment]
Im an idiot, dont know how i missed it was already fixed...
Thanks!

**Comment by frenck** [comment]
Closing it, will be part of the next release.

../Frenck
