### ISSUE TITLE
Enabling flow logging for a tailnet breaks HomeAssistant's ability to connect to it

### ISSUE THREAD

**Issue by QuinnyPig** [hassio-addons/addon-tailscale#211]
Once I enabled flow logging for the tailnet, my node itself dropped off the network.

The message thrown by the add-on reads "Failed Operation: backend error: tailnet requires logging to be enabled. Remove --no-logs-no-support from tailscaled command line."

**Comment by lmagyar** [comment]
It was part of #138, see [#138/files](https://github.com/hassio-addons/addon-tailscale/pull/138/files), I made that PR.

It seems to be a solution to drop `--no-logs-no-support` when 'log_level' is set to 'debug'. What do you think?

**Comment by lmagyar** [comment]
Merged the above PR into my fork. _(This is a drop-in replacement for the official add-on. To be obsolete in the near future.)_

You can test it installing from: https://github.com/lmagyar/homeassistant-addon-tailscale

**Comment by lmagyar** [comment]
PR #212 tries to fix this.

**Comment by lmagyar** [comment]
PR #212 still tries to fix this.

**Comment by lmagyar** [comment]
PR #212 still tries to fix this.
