### ISSUE TITLE
Bump Tailscale version to latest

### ISSUE THREAD

**Issue by eliliam** [hassio-addons/addon-tailscale#214]
# Problem/Motivation

> the add-on version of Tailscale is out of date by multiple minor versions 

## Expected behavior

> be up to date, at least within a minor version or two max

## Actual behavior

> Multiple versions behind Tailscale

## Steps to reproduce

> Install add-on, notice version is 1.38.4 when it should be 1.42.0

## Proposed changes

> Set up a Github action or something that will update the base tailscale dependency every so often

**Comment by frenck** [comment]
The add-on was bumped to the latest version in #207
