### ISSUE TITLE
[BUG] Custom login server doesn't work

### ISSUE THREAD

**Issue by probablypablito** [hassio-addons/addon-tailscale#219]
# Problem/Motivation

The custom login server flag does not work.

## Expected behavior

The server should work.

## Actual behavior

The server does not connect.

## Steps to reproduce

Set a valid, custom server URL in the config tab.

## Proposed changes

The error is: `flag provided but not defined: -login_server`

It seems that a dash was forgotten, although looking at the [source code](https://github.com/hassio-addons/addon-tailscale/blob/f27d247edfe9503117ea425e25a345df55823f16/tailscale/rootfs/etc/s6-overlay/s6-rc.d/post-tailscaled/run#L45) shows otherwise.

**Comment by lmagyar** [comment]
See #184, though it is not released yet (due to a blocking issue).

**Comment by frenck** [comment]
Closing, as this was fixed in #184
