### ISSUE TITLE
Unable to use subnet routing or exit node

### ISSUE THREAD

**Issue by danmed** [hassio-addons/addon-tailscale#22]
# Problem/Motivation

Still unable to use subnet routing or exit node

## Expected behavior

Should be able to route to 192.168.2.0/24

## Actual behavior

Unable to route to specified subnet. Tailscale informs that ip forwarding is not configured.

## Steps to reproduce

Run Home Assistant Operating System on a VM in Proxmox
Install addon

![image](https://user-images.githubusercontent.com/3878490/131583536-8ee093ce-9501-414b-a345-19e903d256e1.png)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by lkroeker** [comment]
Same behaviour with HAOS on a Synology VM.

**Comment by johanPO** [comment]
I have the same, running home assisitant on the Hass IO  (docker)

**Comment by incarvr6** [comment]
Same problem. Running on HA OS on NUC.

**Comment by voodoobg** [comment]
The same with me, have only access to HA, but not the other part of the subnet.

**Comment by Gluxur** [comment]
Same here with a rpi3.
No more sucess with https://github.com/tsujamin/hass-addons

IP forwarding is disable.


2021/09/08 20:32:41 logpolicy: using system state directory "/var/lib/tailscale"
logpolicy.Read /var/lib/tailscale/tailscaled.log.conf: open /var/lib/tailscale/tailscaled.log.conf: no such file or directory
2021/09/08 20:32:41 wgengine.NewUserspaceEngine(tun "tailscale0") ...
2021/09/08 20:32:41 router: v6nat = true
2021/09/08 20:32:41 dns: [rc=unknown ret=dns.directManager]
2021/09/08 20:32:41 dns: using dns.directManager
2021/09/08 20:32:41 link state: interfaces.State{defaultRoute=wlan0 ifs={docker0:[172.17.0.1/16] hassio:[172.30.32.1/23] wlan0:[192.168.43.120/24] ztzlgevf3e:[10.147.18.148/24]} v4=true v6=false}
2021/09/08 20:32:41 Creating wireguard device...
2021/09/08 20:32:41 Bringing wireguard device up...
2021/09/08 20:32:41 external route: up
2021/09/08 20:32:41 Bringing router up...
[20:32:41] INFO: Starting NGinx...
2021/09/08 20:32:41 Clearing router settings...
2021/09/08 20:32:41 Starting link monitor...
2021/09/08 20:32:41 Starting magicsock...
2021/09/08 20:32:41 Engine created.
2021/09/08 20:32:41 monitor: RTM_NEWROUTE: src=, dst=ff00::/8, gw=, outif=31, table=255
2021/09/08 20:32:41 Listening on /var/run/tailscale/tailscaled.sock
2021/09/08 20:32:41 monitor: RTM_NEWROUTE: src=, dst=fe80::/64, gw=, outif=31, table=254
2021/09/08 20:32:41 monitor: RTM_NEWROUTE: src=, dst=fe80::c5a9:b436:795a:3e12/128, gw=, outif=31, table=255
2021/09/08 20:32:42 netmap packet filter: (not ready yet)
2021/09/08 20:32:42 Start
2021/09/08 20:32:42 using backend prefs
2021/09/08 20:32:42 backend prefs for "_daemon": Prefs{ra=true dns=true want=true routes=[0.0.0.0/0 ::/0 192.168.43.0/24] snat=true nf=on host="homeassistant" Persist{lm=, o=[RSXhf], n=[+6/tI] u="gabriel.bergier@gmail.com"}}
2021/09/08 20:32:42 got initial portlist info in 1ms
2021/09/08 20:32:42 magicsock: disco key = d:895724b8b4cdc39c
2021/09/08 20:32:42 control: HostInfo: {"IPNVersion":"1.14.0-t5cff36945-g809e87bba","BackendLogID":"12786a708fc3dcd672f7046d1752f6a7389238d1e0acab01f6c80fce342791bf","OS":"linux","OSVersion":"Alpine Linux v3.14; kernel=5.10.17-v8; container","Hostname":"homeassistant","GoArch":"arm64","RoutableIPs":["0.0.0.0/0","::/0","192.168.43.0/24"],"Services":[{"Proto":"tcp","Port":1883},{"Proto":"tcp","Port":1884},{"Proto":"tcp","Port":4357},{"Proto":"tcp","Port":5355},{"Proto":"tcp","Port":8123},{"Proto":"tcp","Port":8485},{"Proto":"tcp","Port":8883},{"Proto":"tcp","Port":8884},{"Proto":"tcp","Port":9993},{"Proto":"tcp","Port":50219},{"Proto":"tcp","Port":50220}]}
2021/09/08 20:32:42 Backend: logs: be:12786a708fc3dcd672f7046d1752f6a7389238d1e0acab01f6c80fce342791bf fe:
2021/09/08 20:32:42 control: client.Login(false, 0)
2021/09/08 20:32:42 control: authRoutine: state:new; goal=nil paused=false
2021/09/08 20:32:42 control: mapRoutine: state:new
2021/09/08 20:32:42 control: authRoutine: state:new; wantLoggedIn=true
2021/09/08 20:32:42 control: direct.TryLogin(token=false, flags=0)
2021/09/08 20:32:42 control: doLogin(regen=false, hasUrl=false)
2021/09/08 20:32:42 logtail: dialed "log.tailscale.io:443" in 491ms
2021/09/08 20:32:42 netmap packet filter: (not ready yet)
2021/09/08 20:32:42 control: control server key 9e5156a4c65121306dd2d8ed8f92cb8d738e2533011344b522c5d28409bc4970 from https://controlplane.tailscale.com
2021/09/08 20:32:42 control: RegisterReq: onode=[RSXhf] node=[+6/tI] fup=false
2021/09/08 20:32:42 control: RegisterReq: got response; nodeKeyExpired=false, machineAuthorized=true; authURL=false
2021/09/08 20:32:42 control: No AuthURL
2021/09/08 20:32:42 authReconfig: netmap not yet valid. Skipping.
2021/09/08 20:32:42 control: authRoutine: state:authenticated; goal=nil paused=false
2021/09/08 20:32:42 control: mapRoutine: new map needed while idle.
2021/09/08 20:32:42 control: mapRoutine: state:authenticated
2021/09/08 20:32:43 active login: gabriel.bergier@gmail.com
2021/09/08 20:32:43 netmap packet filter: 1 filters
2021/09/08 20:32:43 Switching ipn state NoState -> Starting (WantRunning=true, nm=true)
2021/09/08 20:32:43 health("overall"): error: state=Starting, wantRunning=true
2021/09/08 20:32:43 magicsock: SetPrivateKey called (init)
2021/09/08 20:32:43 wgengine: Reconfig: configuring userspace wireguard config (with 0/6 peers)
2021/09/08 20:32:43 wgengine: Reconfig: configuring router
2021/09/08 20:32:43 control: HostInfo: {"IPNVersion":"1.14.0-t5cff36945-g809e87bba","BackendLogID":"12786a708fc3dcd672f7046d1752f6a7389238d1e0acab01f6c80fce342791bf","OS":"linux","OSVersion":"Alpine Linux v3.14; kernel=5.10.17-v8; container","Hostname":"homeassistant","GoArch":"arm64","RoutableIPs":["0.0.0.0/0","::/0","192.168.43.0/24"]}
2021/09/08 20:32:43 monitor: RTM_NEWROUTE: src=, dst=fd7a:115c:a1e0::/48, gw=, outif=31, table=52
2021/09/08 20:32:43 monitor: RTM_NEWROUTE: src=100.93.177.88/0, dst=100.93.177.88/32, gw=, outif=31, table=255
2021/09/08 20:32:43 [RATELIMIT] format("monitor: %s: src=%v, dst=%v, gw=%v, outif=%v, table=%v")
2021/09/08 20:32:43 wgengine: Reconfig: configuring DNS
2021/09/08 20:32:43 dns: Set: {DefaultResolvers:[] Routes:{} SearchDomains:[] Hosts:6}
2021/09/08 20:32:43 dns: Resolvercfg: {Routes:{} Hosts:6 LocalDomains:[]}
2021/09/08 20:32:43 dns: OScfg: {Nameservers:[] SearchDomains:[] MatchDomains:[]}
2021/09/08 20:32:43 peerapi: serving on http://100.93.177.88:41678
2021/09/08 20:32:43 peerapi: serving on http://[fd7a:115c:a1e0:ab12:4843:cd96:625d:b158]:41678
2021/09/08 20:32:43 control: HostInfo: {"IPNVersion":"1.14.0-t5cff36945-g809e87bba","BackendLogID":"12786a708fc3dcd672f7046d1752f6a7389238d1e0acab01f6c80fce342791bf","OS":"linux","OSVersion":"Alpine Linux v3.14; kernel=5.10.17-v8; container","Hostname":"homeassistant","GoArch":"arm64","RoutableIPs":["0.0.0.0/0","::/0","192.168.43.0/24"],"Services":[{"Proto":"peerapi4","Port":41678},{"Proto":"peerapi6","Port":41678}]}
2021/09/08 20:32:43 Received error: PollNetMap: EOF
2021/09/08 20:32:43 control: mapRoutine: backoff: 12 msec
2021/09/08 20:32:43 control: mapRoutine: state:authenticated
2021/09/08 20:32:43 Received error: PollNetMap: EOF
2021/09/08 20:32:43 control: mapRoutine: backoff: 38 msec
2021/09/08 20:32:43 control: mapRoutine: state:authenticated
2021/09/08 20:32:44 Received error: PollNetMap: EOF
2021/09/08 20:32:44 control: mapRoutine: backoff: 77 msec
2021/09/08 20:32:44 control: mapRoutine: state:authenticated
2021/09/08 20:32:44 [RATELIMIT] format("control: mapRoutine: %s")
2021/09/08 20:32:44 Received error: PollNetMap: EOF
2021/09/08 20:32:44 control: mapRoutine: backoff: 227 msec
2021/09/08 20:32:44 Received error: PollNetMap: EOF
2021/09/08 20:32:44 [RATELIMIT] format("Received error: %v")
2021/09/08 20:32:44 control: mapRoutine: backoff: 360 msec
2021/09/08 20:32:44 [RATELIMIT] format("control: %s: backoff: %d msec")
false
2021/09/08 20:32:45 magicsock: home is now derp-4 (fra)
2021/09/08 20:32:45 magicsock: adding connection to derp-4 for home-keep-alive
2021/09/08 20:32:45 magicsock: 1 active derp conns: derp-4=cr0s,wr0s
2021/09/08 20:32:45 control: NetInfo: NetInfo{varies=false hairpin=false ipv6=false udp=true derp=#4 portmap= link=""}
2021/09/08 20:32:45 Switching ipn state Starting -> Running (WantRunning=true, nm=true)
2021/09/08 20:32:45 derphttp.Client.Connect: connecting to derp-4 (fra)
2021/09/08 20:32:45 magicsock: endpoints changed: 37.171.169.98:27624 (stun), 172.17.0.1:50588 (local), 172.30.32.1:50588 (local), 192.168.43.120:50588 (local)
2021/09/08 20:32:45 control: client.newEndpoints(0, [37.171.169.98:27624 172.17.0.1:50588 172.30.32.1:50588 192.168.43.120:50588])
2021/09/08 20:32:45 magicsock: derp-4 connected; connGen=1
2021/09/08 20:32:45 health("overall"): ok
2021/09/08 20:32:45 wgengine: idle peer d:f506bdcf723561e0 now active, reconfiguring wireguard
2021/09/08 20:32:45 wgengine: Reconfig: configuring userspace wireguard config (with 1/6 peers)
2021/09/08 20:32:45 magicsock: ParseEndpoint: key=[0Leqq]: disco=d:f506bdcf723561e0; derp=4(fra) aip=100.91.218.5 aip=fd7a:115c:a1e0:ab12:4843:cd96:625b:da05 ep=192.168.1.46:41971 ep=90.66.112.90:41971 ep=192.168.31.247:41971 
2021/09/08 20:32:45 magicsock: DERP packet received from idle peer [0Leqq]; created=true
2021/09/08 20:32:46 Accept: TCP{100.91.218.5:44030 > 100.93.177.88:8123} 660 tcp non-syn
2021/09/08 20:32:46 Accept: TCP{100.93.177.88:8123 > 100.91.218.5:44030} 52 ok out
2021/09/08 20:32:47 Accept: TCP{100.91.218.5:44034 > 100.93.177.88:8123} 60 tcp ok
true
Warning: net.ipv6.conf.all.forwarding is disabled.
Subnet routes won't work without IP forwarding.
See https://tailscale.com/kb/1104/enable-ip-forwarding/

**Comment by yousaf465** [comment]
> The same with me, have only access to HA, but not the other part of the subnet.

same issue, can access HA on rpi with local IP 192.168.x.xx but can't access other devices on same subnet.

**Comment by Mjohannesson** [comment]
The same with me, have only access to HA, but not the other part of the subnet.

same issue, can access HA on rpi4 with local IP 192.168.x.xx but can't access other devices on same subnet.

**Comment by TxBillbr** [comment]
same issue

**Comment by Gluxur** [comment]
After a few day of testing, Subnet is working with tsujamin Addon if I check  userspace_networking. 

https://github.com/tsujamin/hass-addons/tree/main/tailscale

**Comment by kylegordy** [comment]
I too am seeing this on my Raspberry Pi running HA OS.

**Comment by yousaf465** [comment]
> > After a few day of testing, Subnet is working with tsujamin Addon if I check userspace_networking.
> > https://github.com/tsujamin/hass-addons/tree/main/tailscale
> 
> I can confirm, this addon works as expected and i have access to the subnet.

what configuration you used for it to work? e.g 192.168.1.0/24 will enable access to 192.168.1.1 and 192.168.1.xx?

**Comment by yousaf465** [comment]
> > > > After a few day of testing, Subnet is working with tsujamin Addon if I check userspace_networking.
> > > > https://github.com/tsujamin/hass-addons/tree/main/tailscale
> > > 
> > > 
> > > I can confirm, this addon works as expected and i have access to the subnet.
> > 
> > 
> > what configuration you used for it to work? e.g 192.168.1.0/24 will enable access to 192.168.1.1 and 192.168.1.xx?
> 
> Yes. (Don't forget to enable it on https://login.tailscale.com )
> If you want to enable only one you could use 192.168.1.1/32

thanks working for me too.

**Comment by s-e-t-h** [comment]
What does the /32 or /24 mean?

Thanks

**Comment by s-e-t-h** [comment]
> > What does the /32 or /24 mean?
> > Thanks
> 
> The slash 24 or /32 refers to the subnet mask of the network, most residential networks use /24 by default, and would address all devices on the network(10.0.0.0/24 would mean all devices with an ip address from 10.0.0.1 to 10.0.0.254). /32 is used to refer to a specific device eg 10.0.0.25/32 would mean the single device 10.0.0.25. https://en.wikipedia.org/wiki/Subnetwork

Thank you so much!

**Comment by ahmadtawakol** [comment]
Just wanted to confirm that @moritzgloeckl fork works perfectly. I've been using it for 2 weeks on 3 Home Assistant instances and haven't had any problems.

**Comment by frenck** [comment]
Fixed in v0.3.0

Tested on a Home Assistant Blue and a Supervised installation.
