### ISSUE TITLE
Failed to install add-on  Hassio on Generic x86-64

### ISSUE THREAD

**Issue by djaksic84** [hassio-addons/addon-tailscale#220]
Hi,

I've managed to install addon on different machines ruunih hassio. But for this particular one I always get the same error:

Failed to install add-on
Can't install ghcr.io/hassio-addons/tailscale/amd64:0.11.1: 404 Client Error for http+docker://localhost/v1.42/images/ghcr.io/hassio-addons/tailscale/amd64:0.11.1/json: Not Found ("No such image: ghcr.io/hassio-addons/tailscale/amd64:0.11.1")

Can someone help me or give advice.

Thank you in advance,

Dusan

**Comment by lmagyar** [comment]
Isn't it just a temporary github download issue? I've successfully pulled that image just now.
