### ISSUE TITLE
Tailscale Cert?

### ISSUE THREAD

**Issue by spooknik** [hassio-addons/addon-tailscale#221]
Hello! 

Would it be possible to somehow run the `tailscale cert {domain}` command? I would like to make an ssl cert for my tailnet.

**Comment by lmagyar** [comment]
See #137, though it is unreleased due to a blocking issue. It will get the cert and start the internal tailscale proxy with it.

**Comment by lmagyar** [comment]
Until it is released, install my fork (drop in replacement), it contains all the unreleased changes, a "seems-to-be-working" workaround for the blocking issue, and some more "hope-to-be-once-merged" PR-s also https://github.com/lmagyar/homeassistant-addon-tailscale If you have any issue with the certificate stuff, open an issue in that repo.

**Comment by JVTEAM** [comment]
Does this issue have to do with the fact that I can get the Home Assistant android app to connect?

I get a "The Home Assistant Hostname certificate mismatch, please review the Home Assistant certificate or the connection settings and try again"

**Comment by frederickjh** [comment]
@lmagyar  After adding your repo do you need to uninstall the mainline version of the tailscale addon or just update and yours will be installed?

**Comment by lmagyar** [comment]
After adding a new repo, wait a little, refresh page, you will see a new add-on, named "Tailscale with features", install it, then:
- stop the official add-on and turn off "Start on boot" and "Watchdog" on the Info page, this way you will be notified when a new version of the official add-on is released
- start the forked version

OK, I see, the "drop in replacement" is misleading: mine is another add-on (in HA, every add-on is a standalone thing, though mine is a forked/modified version of the official), you can install it parallel with the official, but please start only one of them (official or my forked version), better not to mess up networking settings of HA. :)
