### ISSUE TITLE
flag provided but not defined: -login_server

### ISSUE THREAD

**Issue by Bleala** [hassio-addons/addon-tailscale#224]
# Problem/Motivation

Hello,
I've got a problem with the tailscale addon, i can't specify my headscale server, because if i do so, then i get the following error message:
flag provided but not defined: -login_server

I think there is a problem, because the login server flag should look like this: `--login-server`

## Expected behavior

Working flag

## Actual behavior

False flag

## Steps to reproduce

Start the tailscale addon in home assistant and set a custom login server

## Proposed changes

Fix the flag 

I hope someone can fix this flag issue :)

Greetings

**Comment by frenck** [comment]
fixed in #184
