### ISSUE TITLE
Connection to SmartThings 

### ISSUE THREAD

**Issue by JVTEAM** [hassio-addons/addon-tailscale#226]
# Problem/Motivation

Moving away from DuckDNS as this is a much safer alternative.  However, smartthings requires external access.  Wondering if I can reconnect the smartthings devices without it.

## Expected behavior

Would like to reconnect smartthings and have it act like the DuckDNS device

## Actual behavior

Smartthings does not connect

## Proposed changes

This may be impossible due to cloud based nature of smartthings, but looking for some direction

**Comment by lmagyar** [comment]
Do yo want to access your Home Assistant device through Tailscale VPN but from a general machine without a Tailscale client? You need Tailscale Funnel (https://tailscale.com/kb/1223/tailscale-funnel/).

There is PR #197 to implement it in the official add-on. Until it is merged, you can test it in my fork: https://github.com/lmagyar/homeassistant-addon-tailscale
