### ISSUE TITLE
specifing a custom login server does not work 

### ISSUE THREAD

**Issue by grievertime** [hassio-addons/addon-tailscale#227]
# Problem/Motivation

specifing a custom login server does not work with error 
`flag provided but not defined: -login_server`
seems like a bad formatting of the string in the `tailscale up` command

## Expected behavior

should start with correct login server

## Steps to reproduce

> specify a custom login server in the configuration tab

**Comment by lmagyar** [comment]
See #184, though it is not released yet (due to a blocking issue).

**Comment by grievertime** [comment]
> See #184, though it is not released yet (due to a blocking issue).

Oh thank you, now I see. What is the blocking issue?

**Comment by lmagyar** [comment]
Blocking issue is not related to login server. #181 drops userspace networking, but when user misconfigures it's Tailnet, this can soft-brick the HA device. I've made a (hacky) workaround for this in #201. Until this situation is resolved, you can use my fork at: https://github.com/lmagyar/homeassistant-addon-tailscale

**Comment by ss89** [comment]
please unstale

**Comment by SkipTam** [comment]
Hi, still have the same issue. Debug mode does not give any information. When i Click on the Login Button from the Webserver i get forwarded to the logoin page of Tailscale

**Comment by MadWalnut** [comment]
Same issue here. The fork works nicely for now, but merging #201 would be great.

**Comment by MadWalnut** [comment]
Unstale please

**Comment by frenck** [comment]
Fixed in https://github.com/hassio-addons/addon-tailscale/releases/tag/v0.12.0
