### ISSUE TITLE
JS Error When Attempting to Open Login Page

### ISSUE THREAD

**Issue by cguess** [hassio-addons/addon-tailscale#258]
# Problem/Motivation

After an initial install, clicking the "Log in" button results in a JS popup error saying "Failed operation: null is not an object (evaluating 'window.open(url, "_blank").focus')" and nothing else. This prevents me from logging in.

## Expected behavior

I'm not 100% sure but I assume it redirects to a login page for Tailscale

## Actual behavior

Clicking the "Log in" button results in a JS popup error saying "Failed operation: null is not an object (evaluating 'window.open(url, "_blank").focus')"

## Steps to reproduce

Install the plugin on an up to date version of Home Assistant, enable the sidebar icon, then click "Log in"

## Proposed changes

Unsure, I haven't dug into the codebase.

**Comment by lmagyar** [comment]
I think you are using an iOS device, see DOCS:

> Note: Some browsers don't work with this step. It is recommended to complete this step on a desktop or laptop computer using the Chrome browser.

There is the unmerged PR #198 to provide a better popup message.
