### ISSUE TITLE
Cannot connect to Tailscale using an authentication key

### ISSUE THREAD

**Issue by laenbdarceq** [hassio-addons/addon-tailscale#266]
# Problem/Motivation

I need to be able to connect to my Tailscale account using an [authentication key](https://tailscale.com/kb/1085/auth-keys/) instead of the regular flow with the link generated in the logs.

## Expected behavior

I expect a configuration parameter named (for example) `auth_key` that, when set, will add the `--auth-key <auth_key>` flag to the `tailscale up` command

## Actual behavior

There is no way to use an auth key to connect to Tailscale

## Steps to reproduce

Just follow the documentation to start the addon

## Proposed changes

I have changes that I tested on my Home Assistant instance that I can submit through a pull request, if you think it makes sense. 

It just adds an option in `config.yaml` and `translations/en.yaml` and uses it in `tailscale/rootfs/etc/s6-overlay/s6-rc.d/post-tailscaled/run` to add the `--auth-key` flag with the provided auth key to the `tailscale up` command. Does nothing if the option is unset. Documentation is also updated.

**Comment by laenbdarceq** [comment]
> I've implemented it also, then merged your branch (with modifications) to preserve your name also (I've got inspiration for the docs wording, the hardest part).

That is very nice of you, thanks !
 
> Until the PR is merged here (currently it is draft, there are more important bugfixes in the official queue), it can be tested installing my fork at https://github.com/lmagyar/homeassistant-addon-tailscale

Will do, thanks.

**Comment by frenck** [comment]
I'm blocking the PR right now, mostly because I'd like to understand "Why".

Just adding options to an add-on, "because we can", isn't right IMHO. I strongly want all the add-ons to have a "the fewer options the better"-approach. With that in mind, I don't understand the reason why I would add this option to the add-on?

../Frenck

**Comment by lmagyar** [comment]
@laenbdarceq @Klariff Could you please describe why this auth_key option is needed? Why the standard WebUI doesn't work for you for authentication? Why do you try to use the link generated in the logs instead of the add-on's WebUI?

**Comment by laenbdarceq** [comment]
@lmagyar @frenck To be honest, I was basically just blindly following the advice from the Tailscale documentation to connect servers to the network using an auth_key (since Home Assistant is a server). It's probably not needed for the common use case indeed. It allows automatic tagging and acls. 
I can probably agree that, if you want to keep it as simple as possible for end users, this should be left aside. I'm more on the side of as few hardcoding as possible, and providing a sane set of default option values (hiding away most of them for advanced use only), but it's just my (very) humble opinion (and definitely not criticism).

**Comment by lmagyar** [comment]
I closed the PR because this modification is not needed, and I think this issue can be closed also.
