### ISSUE TITLE
Tailscale package is outdated

### ISSUE THREAD

**Issue by northalpha** [hassio-addons/addon-tailscale#268]
I can see that the in source the latest tailscale package is referenced:

https://github.com/hassio-addons/addon-tailscale/blob/c769e3752e917b9b6f29794a7d2385ed7bddcdaa/tailscale/Dockerfile#L10

but using the release version of this addon, tailscale `1.38.4` is shipped. may i ask to release an new version of this addon with these changes?

Thanks for this great Addon!

**Comment by lmagyar** [comment]
See: #246 #214

**Comment by northalpha** [comment]
i havw switched to your addon.
