### ISSUE TITLE
API has changed.  Need Derp field removed

### ISSUE THREAD

**Issue by JVTEAM** [hassio-addons/addon-tailscale#269]
Logger: homeassistant.components.tailscale
Source: helpers/update_coordinator.py:290
Integration: Tailscale ([documentation](https://www.home-assistant.io/integrations/tailscale), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+tailscale%22))
First occurred: October 10, 2023 at 2:37:56 PM (704 occurrences)
Last logged: 6:45:24 AM

Unexpected error fetching tailscale data: 19 validation errors for Devices devices -> 3986529723163788 -> clientConnectivity -> derp field required (type=value_error.missing) devices -> 4150023481503342 -> clientConnectivity -> derp field required (type=value_error.missing) devices -> 8377641693760812 -> clientConnectivity -> derp field required (type=value_error.missing) devices -> 1217976137773628 -> clientConnectivity -> derp field required (type=value_error.missing) devices -> 204887244939389 -> clientConnectivity -> derp field required (type=value_error.missing) devices -> 6931645781658501 -> clientConnectivity -> derp field required (type=value_error.missing) devices -> 5416345667005608 -> clientConnectivity -> derp field required (type=value_error.missing) devices -> 8047231513927154 -> clientConnectivity -> derp field required (type=value_error.missing) devices -> 4903198163168579 -> clientConnectivity -> derp field required (type=value_error.missing) devices -> 1393886256242854 -> clientConnectivity -> derp field required (type=value_error.missing) devices -> 6113972241862281 -> clientConnectivity -> derp field required (type=value_error.missing) devices -> 992772308704955 -> clientConnectivity -> derp field required (type=value_error.missing) devices -> 5321323842336203 -> clientConnectivity -> derp field required (type=value_error.missing) devices -> 4886936953038663 -> clientConnectivity -> derp field required (type=value_error.missing) devices -> 3352266320564933 -> clientConnectivity -> derp field required (type=value_error.missing) devices -> 7966970622257929 -> clientConnectivity -> derp field required (type=value_error.missing) devices -> 1100843917255132 -> clientConnectivity -> derp field required (type=value_error.missing) devices -> 2450214712208937 -> clientConnectivity -> derp field required (type=value_error.missing) devices -> 7767661327468001 -> clientConnectivity -> derp field required (type=value_error.missing)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 290, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/tailscale/coordinator.py", line 37, in _async_update_data
    return await self.tailscale.devices()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/tailscale/tailscale.py", line 116, in devices
    return Devices.parse_obj(data).devices
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "pydantic/main.py", line 526, in pydantic.main.BaseModel.parse_obj
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 19 validation errors for Devices
devices -> 3986529723163788 -> clientConnectivity -> derp
  field required (type=value_error.missing)
devices -> 4150023481503342 -> clientConnectivity -> derp
  field required (type=value_error.missing)
devices -> 8377641693760812 -> clientConnectivity -> derp
  field required (type=value_error.missing)
devices -> 1217976137773628 -> clientConnectivity -> derp
  field required (type=value_error.missing)
devices -> 204887244939389 -> clientConnectivity -> derp
  field required (type=value_error.missing)
devices -> 6931645781658501 -> clientConnectivity -> derp
  field required (type=value_error.missing)
devices -> 5416345667005608 -> clientConnectivity -> derp
  field required (type=value_error.missing)
devices -> 8047231513927154 -> clientConnectivity -> derp
  field required (type=value_error.missing)
devices -> 4903198163168579 -> clientConnectivity -> derp
  field required (type=value_error.missing)
devices -> 1393886256242854 -> clientConnectivity -> derp
  field required (type=value_error.missing)
devices -> 6113972241862281 -> clientConnectivity -> derp
  field required (type=value_error.missing)
devices -> 992772308704955 -> clientConnectivity -> derp
  field required (type=value_error.missing)
devices -> 5321323842336203 -> clientConnectivity -> derp
  field required (type=value_error.missing)
devices -> 4886936953038663 -> clientConnectivity -> derp
  field required (type=value_error.missing)
devices -> 3352266320564933 -> clientConnectivity -> derp
  field required (type=value_error.missing)
devices -> 7966970622257929 -> clientConnectivity -> derp
  field required (type=value_error.missing)
devices -> 1100843917255132 -> clientConnectivity -> derp
  field required (type=value_error.missing)
devices -> 2450214712208937 -> clientConnectivity -> derp
  field required (type=value_error.missing)
devices -> 7767661327468001 -> clientConnectivity -> derp
  field required (type=value_error.missing)

Review this fix.

https://github.com/frenck/python-tailscale/issues/427

**Comment by bdoell88** [comment]
I am experiencing this same issue.

**Comment by lmagyar** [comment]
Do you experience these problems with the add-on? Or with the integration? These logs are not add-on logs.
See https://github.com/home-assistant/core/issues/101573 and https://github.com/home-assistant/core/issues/101733

**Comment by frenck** [comment]
Not related to the add-on. 

../Frenck

**Comment by bdoell88** [comment]
> Not related to the add-on.
> 
> ../Frenck

Can you expand on this? It seems to be affecting many people, so I'm unsure how its not related to the addon.

**Comment by frenck** [comment]
@bdoell88 It is not. Sorry.
