### ISSUE TITLE
Tailscale Add-on's embedded Nginx proxy intercepts all in-bound HTTPS traffic from tailnet

### ISSUE THREAD

**Issue by miniksa** [hassio-addons/addon-tailscale#276]
# Problem/Motivation

> Can no longer access Nginx Proxy Manager on same host as Tailscale

## Expected behavior

> Setting `funnel: false` and `proxy: false` in the YAML for the Tailscale Add-On should disable its internal Nginx proxy server and instead forward HTTP requests to the Nginx Proxy Manager Add-On on the host.

## Actual behavior

> Setting `funnel:false` and `proxy:false` in the UI and the YAML configuration for the add-on does nothing. It always resets itself to `true` on every restart of the Tailscale Add-On.

## Steps to reproduce

> 1. Install Nginx Proxy Manager add-on and set up reverse proxies for various services on the network. Contact these services remotely over the tailnet and they're fine.
> 2. Install Tailscale add-on and connect it to a tailnet with funnel enabled in the admin panel. Now you cannot access them anymore as the Nginx proxy inside the Tailscale add-on will catch them and say "I don't know what host that is" and fail.

## Proposed changes

> Make it so we can actually turn off funnel and/or proxy, completely disabling the Nginx proxy inside this add-on and resuming forwarding to the HA host device where Nginx Proxy should catch it on port 80/443.

OR

> Make it so I can instead set up an entire list of `tailscale serve` endpoints in the configuration for this add-on so I can use it instead of the Nginx Proxy Manager one.

**Comment by miniksa** [comment]
Aha okay. I wasn't sure if the "off by default" discussion was just a preference or also related to the "off doesn't actually turn it off" thing I was experiencing.

I think allowing a configurable port would be great. I'd happily put the tailscale proxy/funnel on 8443 since I have no other services on the network doing that, let 443 through to Nginx Proxy Manager for all my other services, and I'd be happy. 

I only wanted to turn it off because it was otherwise blocking Nginx Proxy Manager. I like the idea of what it does and I'd more happily use both if they could work in concert.

**Comment by miniksa** [comment]
@lmagyar, I took the 0.13.0 update yesterday and turned off proxy and funnel and I've completely restored my existing 0.11.0 behavior of having Nginx Proxy Manager add-on able to eat up all the HTTPS traffic from the add-on. So that portion of it worked perfectly for me. Thank you!

**Comment by lmagyar** [comment]
PR #277 and #293 address this issue, and they are still open.
