### ISSUE TITLE
High CPu usage

### ISSUE THREAD

**Issue by Welsyntoffie** [hassio-addons/addon-tailscale#284]
# Problem/Motivation
Since HassOS 11.1 cpu usage increases frrom 5% to 26% constant

## Expected behavior
Low CPU usage

Tailscale addon is now at the top of the glances list.

**Comment by frenck** [comment]
If you have a bit of traffic/clients this can/might happen. Tailscale cannot leverage the kernel drivers for Wireguard (which is a Tailscale limitation). From an add-on perspective, there is no much I can do about that.

../Frenck

**Comment by elcajon** [comment]
I can observe the high CPU usage since add-on version v0.13.0 (with the previous version I did not have these CPU problems), but this only occurs when `userspace_networking` is set to false (unrelated to `accept_routes` true/false).

**Comment by frenck** [comment]
Related to: #168

**Comment by Welsyntoffie** [comment]
> I can observe the high CPU usage since add-on version v0.13.0 (with the previous version I did not have these CPU problems), but this only occurs when `userspace_networking` is set to false (unrelated to `accept_routes` true/false).

Well done for picking that up and thank you.
Mine was set to disabled. So I enabled userspace_networking and now my cpu is at 3% connected via funnel (1 device) and 1.6% with no connections.
