### ISSUE TITLE
Unable to select exit node as HA node on peer Tailscale device

### ISSUE THREAD

**Issue by michalw2-alt** [hassio-addons/addon-tailscale#297]
Hello,

I have installed Tailscale instance as part of Home Assistant addon. 
Is there a way I can use it as exit node to be able to access local subnet (for instance my router device at 192.168.1.1) from peer Tailscale node or due to container nature of addon - it does not have access to local networks on HA host?

```
accept_routes: false
advertise_exit_node: true
advertise_routes:
  - 192.168.1.0/24
accept_dns: false
log_level: info
userspace_networking: true
```

Unfortunately for some reason I don't see option to select HA device as exit node on peer Tailscale devices.
Thank you in advance.
Michal

**Comment by lmagyar** [comment]
This works with the default setting. You don't need to edit the yaml at all.

Note: Exit node is for internet access.

To access local server/router, you need subnet routing. The add-on offers it's subnets to Tailscale (usually the 192.168.x.x), but the routing has to be enabled on Tailscale's management console (https://login.tailscale.com/admin/machines click "Edit route settings"). When enabled, other Tailscale ***clients*** will be able to access the 192.168.x.x network on this add-on's host.

If you want to access from this 192.168.x.x server (where Tailscale is ***not*** installed) other Tailscale clients (or their subnets), so the opposite direction, that is a totally different story. In that case you have to disable userspace_networking in the add-on config, this will create a tailscale0 network interface on the add-on's host, and you can set up the routing on the 192.168.x.x server to use this add-on's host as router (the routing on the add-on's host is already set up by Tailscale). But be careful with 192.168.x.x addresses, you won't be able to access another 192.168.x.x domain from this 192.168.x.x server. Tailscale assumes, these are the same networks, and these TS clients are in load-balancing and/or failover, but this will soft-brick this HA host, so there is a quite complex workaround that the add-on intentionally makes any Tailscale routing impossible on the host between these colliding subnets. Note: This has no effect on the incoming connections described in the previous paragraph. Reason: there is a much larger chance, that users will misconfigure their VPN with 192.68.x.x addresses than users want to make load-balanced networks.

**Comment by michalw2-alt** [comment]
Thank you very much for detailed reply. Much appreciated.

> This works with the default setting. You don't need to edit the yaml at all.
> 
> Note: Exit node is for internet access.
> 
> To access local server/router, you need subnet routing. The add-on offers it's subnets to Tailscale (usually the 192.168.x.x), but the routing has to be enabled on Tailscale's management console (https://login.tailscale.com/admin/machines click "Edit route settings"). When enabled, other Tailscale _**clients**_ will be able to access the 192.168.x.x network on this add-on's host.
> 
> If you want to access from this 192.168.x.x server (where Tailscale is _**not**_ installed) other Tailscale clients (or their subnets), so the opposite direction, that is a totally different story. In that case you have to disable userspace_networking in the add-on config, this will create a tailscale0 network interface on the add-on's host, and you can set up the routing on the 192.168.x.x server to use this add-on's host as router (the routing on the add-on's host is already set up by Tailscale). But be careful with 192.168.x.x addresses, you won't be able to access another 192.168.x.x domain from this 192.168.x.x server. Tailscale assumes, these are the same networks, and these TS clients are in load-balancing and/or failover, but this will soft-brick this HA host, so there is a quite complex workaround that the add-on intentionally makes any Tailscale routing impossible on the host between these colliding subnets. Note: This has no effect on the incoming connections described in the previous paragraph. Reason: there is a much larger chance, that users will misconfigure their VPN with 192.68.x.x addresses than users want to make load-balanced networks.

**Comment by michalw2-alt** [comment]
Thank you very much for detailed reply. Much appreciated.
