### ISSUE TITLE
Release the latest Tailscale version 

### ISSUE THREAD

**Issue by DocEmmetBrown** [hassio-addons/addon-tailscale#298]
# Problem/Motivation

Since [this commit](https://github.com/hassio-addons/addon-tailscale/commit/4dc8cfd9404a3fd48a32c01fb93d46e8daf6a6d2), the tailscale version has been bumped to the latest one (`1.54.0`) but not released, so default HA installation is "stuck" with `1.50.1`.

## Expected behavior

Latest package includes latest Tailscale version

## Actual behavior

Current latest package includes outdated version :) 

Thanks a lot for this project

**Comment by frenck** [comment]
Already merged, will be part of the next release of the add-on.
