### ISSUE TITLE
Tailscale incompatible with Mosquitto MQTT server? 

### ISSUE THREAD

**Issue by flipdream** [hassio-addons/addon-tailscale#30]
Installed this add-on on a HA Supervised and Home assistant OS 6.4 installation, all is workings fine, but my networks devices are not able to connect to MQTT server (mosquito addon) when Tailscale addon is running. When Tailscale is stopped all works fine again.

Core 2021.9.7
Supervisor 2021.09.0
HA OS 6.4
Mosquitto broker 6.0.1

**Comment by frenck** [comment]
Please provide a reproduction with settings and logs.

**Comment by flipdream** [comment]
Here you are, thanks in advance

Tailscale default settings 

Mosquitto settings:
logins: []
customize:
  active: false
  folder: mosquitto
certfile: fullchain.pem
keyfile: privkey.pem
require_certificate: false

1883 Normal MQTT
1884 MQTT over WebSocket
8883 Normal MQTT with SSL
8884 MQTT over WebSocket with SSL

MQTT Log:
1632316815: New connection from 192.168.111.50 on port 1883.
{"result": "ok", "data": {}}1632316815: New client connected from 192.168.111.50 as CalefaccioTerm (p2, c1, k15, u'casa').
1632316815: New connection from 192.168.111.55 on port 1883.
1632316815: New client connected from 192.168.111.55 as PowerMonitor (p2, c1, k15, u'casa').
1632316816: New connection from 192.168.111.53 on port 1883.
1632316816: New client connected from 192.168.111.53 as SolarPower (p2, c1, k15, u'casa').
1632316818: New connection from 192.168.111.51 on port 1883.
1632316818: New client connected from 192.168.111.51 as Finestres (p2, c1, k15, u'casa').
1632316819: New connection from 192.168.111.56 on port 1883.
1632316819: New client connected from 192.168.111.56 as Pantalla5P (p2, c1, k15, u'casa').
1632316924: New connection from 172.30.32.2 on port 1883.
1632316924: Socket error on client <unknown>, disconnecting.
1632317044: New connection from 172.30.32.2 on port 1883.
1632317044: Socket error on client <unknown>, disconnecting.
1632317164: New connection from 172.30.32.2 on port 1883.
1632317164: Socket error on client <unknown>, disconnecting.
1632317284: New connection from 172.30.32.2 on port 1883.
1632317284: Socket error on client <unknown>, disconnecting.
1632317315: Socket error on client PowerMonitor, disconnecting.
1632317315: Socket error on client SolarPower, disconnecting.
1632317316: Socket error on client Pantalla5P, disconnecting.
1632317322: Client Finestres has exceeded timeout, disconnecting.
1632317328: Socket error on client CalefaccioTerm, disconnecting.
1632317404: New connection from 172.30.32.2 on port 1883.
1632317404: Socket error on client <unknown>, disconnecting.

Log from Tailscale addon:
2021/09/22 15:28:14 control: client.Login(false, 0)
2021/09/22 15:28:14 control: authRoutine: state:new; wantLoggedIn=true
2021/09/22 15:28:14 control: direct.TryLogin(token=false, flags=0)
2021/09/22 15:28:14 control: doLogin(regen=false, hasUrl=false)
2021/09/22 15:28:14 control: mapRoutine: state:authenticating
false
2021/09/22 15:28:15 control: HostInfo: {"IPNVersion":"1.14.0-t5cff36945-g809e87bba","BackendLogID":"5f78bf30138c83b3fe1722ddfdf01063bf441a06a10e0ede755372aa7f85c2d1","OS":"linux","OSVersion":"Alpine Linux v3.14; kernel=5.10.17-v8; container","Hostname":"homeassistant","GoArch":"arm64","RoutableIPs":["0.0.0.0/0","::/0","192.168.111.0/24"]}
2021/09/22 15:28:15 control: mapRoutine: new map needed while idle.
2021/09/22 15:28:15 control: mapRoutine: state:authenticating
2021/09/22 15:28:16 logtail: dialed "log.tailscale.io:443" in 2.359s
2021/09/22 15:28:16 control: control server key 9e5156a4c65121306dd2d8ed8f92cb8d738e2533011344b522c5d28409bc4970 from https://controlplane.tailscale.com
2021/09/22 15:28:16 control: RegisterReq: onode=[AAxjy] node=[PmY3a] fup=false
2021/09/22 15:28:16 control: RegisterReq: got response; nodeKeyExpired=false, machineAuthorized=true; authURL=false
2021/09/22 15:28:16 control: No AuthURL
2021/09/22 15:28:16 authReconfig: netmap not yet valid. Skipping.
2021/09/22 15:28:16 control: mapRoutine: new map needed while idle.
2021/09/22 15:28:16 control: authRoutine: state:authenticated; goal=nil paused=false
2021/09/22 15:28:16 control: mapRoutine: state:authenticated
2021/09/22 15:28:16 active login: flipdream@gmail.com
2021/09/22 15:28:16 netmap packet filter: 1 filters
2021/09/22 15:28:16 Switching ipn state NoState -> Starting (WantRunning=true, nm=true)
2021/09/22 15:28:16 health("overall"): error: state=Starting, wantRunning=true
2021/09/22 15:28:16 magicsock: SetPrivateKey called (init)
2021/09/22 15:28:16 wgengine: Reconfig: configuring userspace wireguard config (with 1/4 peers)
2021/09/22 15:28:16 magicsock: ParseEndpoint: key=[7imlJ]: disco=d:a76cd50a192d32e2; derp=8(lhr) aip=100.97.83.17 aip=192.168.111.0/24 aip=0.0.0.0/0 aip=::/0 aip=fd7a:115c:a1e0:ab12:4843:cd96:6261:5311 ep=83.34.244.93:41641 ep=172.17.0.1:41641 ep=172.18.0.1:41641 ep=192.168.111.6:41641 
2021/09/22 15:28:16 wgengine: Reconfig: configuring router
2021/09/22 15:28:17 monitor: RTM_NEWROUTE: src=, dst=192.168.111.0/24, gw=, outif=38, table=52
2021/09/22 15:28:17 Accept: TCP{192.168.111.4:1883 > 192.168.111.53:63989} 40 ok out
2021/09/22 15:28:17 magicsock: adding connection to derp-8 for [7imlJ]
2021/09/22 15:28:17 magicsock: 1 active derp conns: derp-8=cr0s,wr0s
2021/09/22 15:28:17 derphttp.Client.Connect: connecting to derp-8 (lhr)
2021/09/22 15:28:17 monitor: RTM_NEWROUTE: src=, dst=fd7a:115c:a1e0::/48, gw=, outif=38, table=52
2021/09/22 15:28:17 [RATELIMIT] format("monitor: %s: src=%v, dst=%v, gw=%v, outif=%v, table=%v")
2021/09/22 15:28:17 magicsock: want call-me-maybe but endpoints stale; restunning
2021/09/22 15:28:17 wgengine: Reconfig: configuring DNS
2021/09/22 15:28:17 dns: Set: {DefaultResolvers:[] Routes:{flipdream.gmail.com.beta.tailscale.net.:[]}+65arpa SearchDomains:[flipdream.gmail.com.beta.tailscale.net.] Hosts:5}
2021/09/22 15:28:17 dns: Resolvercfg: {Routes:{.:[172.30.32.3:53]} Hosts:5 LocalDomains:[flipdream.gmail.com.beta.tailscale.net.]+65arpa}
2021/09/22 15:28:17 dns: OScfg: {Nameservers:[100.100.100.100] SearchDomains:[flipdream.gmail.com.beta.tailscale.net. local.hass.io.] MatchDomains:[]}
2021/09/22 15:28:17 health("dns"): error: rename /etc/resolv.conf /etc/resolv.pre-tailscale-backup.conf: device or resource busy
2021/09/22 15:28:17 peerapi: serving on http://100.78.123.82:59709
2021/09/22 15:28:17 control: controlclient: restarting map request for "dns" health change to new state: rename /etc/resolv.conf /etc/resolv.pre-tailscale-backup.conf: device or resource busy
2021/09/22 15:28:17 peerapi: serving on http://[fd7a:115c:a1e0:ab12:4843:cd96:624e:7b52]:59709
2021/09/22 15:28:17 control: HostInfo: {"IPNVersion":"1.14.0-t5cff36945-g809e87bba","BackendLogID":"5f78bf30138c83b3fe1722ddfdf01063bf441a06a10e0ede755372aa7f85c2d1","OS":"linux","OSVersion":"Alpine Linux v3.14; kernel=5.10.17-v8; container","Hostname":"homeassistant","GoArch":"arm64","RoutableIPs":["0.0.0.0/0","::/0","192.168.111.0/24"],"Services":[{"Proto":"tcp","Port":22},{"Proto":"tcp","Port":53},{"Proto":"tcp","Port":1627},{"Proto":"tcp","Port":1883},{"Proto":"tcp","Port":1884},{"Proto":"tcp","Port":4357},{"Proto":"tcp","Port":5050},{"Proto":"tcp","Port":5355},{"Proto":"tcp","Port":8086},{"Proto":"tcp","Port":8123},{"Proto":"tcp","Port":8182},{"Proto":"tcp","Port":8485},{"Proto":"tcp","Port":8883},{"Proto":"tcp","Port":8884},{"Proto":"tcp","Port":62442},{"Proto":"tcp","Port":64571},{"Proto":"tcp","Port":64841},{"Proto":"tcp","Port":64975,"Description":"nginx: worker process"},{"Proto":"peerapi4","Port":59709},{"Proto":"peerapi6","Port":59709}]}
2021/09/22 15:28:17 Switching ipn state Starting -> Running (WantRunning=true, nm=true)
2021/09/22 15:28:17 control: mapRoutine: state:authenticated
2021/09/22 15:28:17 magicsock: home is now derp-8 (lhr)
2021/09/22 15:28:17 control: NetInfo: NetInfo{varies=false hairpin=false ipv6=false udp=true derp=#8 portmap= link=""}
2021/09/22 15:28:17 magicsock: endpoints changed: 83.34.244.93:56855 (stun), 172.17.0.1:56855 (local), 172.30.32.1:56855 (local), 192.168.111.4:56855 (local)
2021/09/22 15:28:17 magicsock: STUN done; sending call-me-maybe to d:a76cd50a192d32e2 [7imlJ]
2021/09/22 15:28:17 control: client.newEndpoints(0, [83.34.244.93:56855 172.17.0.1:56855 172.30.32.1:56855 192.168.111.4:56855])
2021/09/22 15:28:17 magicsock: derp-8 connected; connGen=1
2021/09/22 15:28:17 Accept: ICMPv4{192.168.111.4:0 > 192.168.111.6:0} 148 ok out
2021/09/22 15:28:17 Accept: ICMPv4{192.168.111.4:0 > 192.168.111.6:0} 148 ok out
2021/09/22 15:28:17 control: mapRoutine: state:authenticated
2021/09/22 15:28:17 [RATELIMIT] format("control: mapRoutine: %s")
2021/09/22 15:28:17 control: HostInfo: {"IPNVersion":"1.14.0-t5cff36945-g809e87bba","BackendLogID":"5f78bf30138c83b3fe1722ddfdf01063bf441a06a10e0ede755372aa7f85c2d1","OS":"linux","OSVersion":"Alpine Linux v3.14; kernel=5.10.17-v8; container","Hostname":"homeassistant","GoArch":"arm64","RoutableIPs":["0.0.0.0/0","::/0","192.168.111.0/24"],"Services":[{"Proto":"tcp","Port":22},{"Proto":"tcp","Port":53},{"Proto":"tcp","Port":1627},{"Proto":"tcp","Port":1883},{"Proto":"tcp","Port":1884},{"Proto":"tcp","Port":4357},{"Proto":"tcp","Port":5050},{"Proto":"tcp","Port":5355},{"Proto":"tcp","Port":8086},{"Proto":"tcp","Port":8123},{"Proto":"tcp","Port":8182},{"Proto":"tcp","Port":8485},{"Proto":"tcp","Port":8883},{"Proto":"tcp","Port":8884},{"Proto":"tcp","Port":59709,"Description":"tailscaled"},{"Proto":"tcp","Port":62442},{"Proto":"tcp","Port":64571},{"Proto":"tcp","Port":64841},{"Proto":"tcp","Port":64975,"Description":"nginx: worker process"},{"Proto":"peerapi4","Port":59709},{"Proto":"peerapi6","Port":59709}],"NetInfo":{"MappingVariesByDestIP":false,"HairPinning":false,"WorkingIPv6":false,"WorkingUDP":true,"UPnP":false,"PMP":false,"PCP":false,"PreferredDERP":8,"DERPLatency":{"1-v4":0.112339942,"10-v4":0.180495615,"11-v4":0.222501534,"12-v4":0.130006626,"2-v4":0.185346955,"3-v4":0.165748768,"4-v4":0.04992811,"5-v4":0.328048744,"6-v4":0.185502952,"7-v4":0.280877678,"8-v4":0.039479074,"9-v4":0.135198886}}}
true
Warning: net.ipv6.conf.all.forwarding is disabled.
Subnet routes won't work without IP forwarding.
See https://tailscale.com/kb/1104/enable-ip-forwarding/
2021/09/22 15:28:22 magicsock: disco: node [7imlJ] d:a76cd50a192d32e2 now using 192.168.111.6:41641
2021/09/22 15:28:27 Accept: TCP{192.168.111.4:43100 > 192.168.111.167:6053} 40 ok out
2021/09/22 15:28:28 open-conn-track: timeout opening (TCP 100.78.123.82:32874 => 192.168.111.169:6053) to node [7imlJ]; online=yes, lastRecv=12s
2021/09/22 15:28:31 open-conn-track: timeout opening (TCP 100.78.123.82:53640 => 192.168.111.157:6668) to node [7imlJ]; online=yes, lastRecv=2s
2021/09/22 15:28:31 open-conn-track: timeout opening (TCP 100.78.123.82:32874 => 192.168.111.169:6053) to node [7imlJ]; online=yes, lastRecv=3s
2021/09/22 15:28:32 open-conn-track: timeout opening (TCP 100.78.123.82:40710 => 192.168.111.167:6053) to node [7imlJ]; online=yes, lastRecv=3s
2021/09/22 15:28:32 open-conn-track: timeout opening (TCP 100.78.123.82:40712 => 192.168.111.167:6053) to node [7imlJ]; online=yes, lastRecv=3s
2021/09/22 15:28:32 [RATELIMIT] format("open-conn-track: timeout opening %v to node %v; online=%v, lastRecv=%v")
2021/09/22 15:28:37 Accept: TCP{192.168.111.4:1883 > 192.168.111.53:51124} 48 ok out
2021/09/22 15:28:39 [RATELIMIT] format("open-conn-track: timeout opening %v to node %v; online=%v, lastRecv=%v") (3 dropped)
2021/09/22 15:28:39 open-conn-track: timeout opening (TCP 100.78.123.82:53344 => 192.168.111.170:6053) to node [7imlJ]; online=yes, lastRecv=0s
2021/09/22 15:28:40 open-conn-track: timeout opening (TCP 100.78.123.82:55814 => 192.168.111.166:6053) to node [7imlJ]; online=yes, lastRecv=2s
2021/09/22 15:28:40 [RATELIMIT] format("open-conn-track: timeout opening %v to node %v; online=%v, lastRecv=%v")
2021/09/22 15:28:47 Accept: TCP{192.168.111.4:1883 > 192.168.111.56:53810} 48 ok out
2021/09/22 15:28:57 Accept: TCP{192.168.111.4:1883 > 192.168.111.55:53112} 48 ok out
2021/09/22 15:29:04 open-conn-track: flow TCP (TCP 100.78.123.82:39470 => 192.168.111.53:6053) got RST by peer
2021/09/22 15:29:05 open-conn-track: timeout opening (TCP 100.78.123.82:59624 => 192.168.111.160:6668) to node [7imlJ]; online=yes, lastRecv=7s
2021/09/22 15:29:05 open-conn-track: timeout opening (TCP 100.78.123.82:43694 => 192.168.111.159:6668) to node [7imlJ]; online=yes, lastRecv=7s
2021/09/22 15:29:05 open-conn-track: timeout opening (TCP 100.78.123.82:38650 => 192.168.111.158:6668) to node [7imlJ]; online=yes, lastRecv=7s
2021/09/22 15:29:05 open-conn-track: timeout opening (TCP 100.78.123.82:34336 => 192.168.111.156:6668) to node [7imlJ]; online=yes, lastRecv=7s
2021/09/22 15:29:07 Accept: TCP{192.168.111.4:43100 > 192.168.111.167:6053} 40 ok out
2021/09/22 15:29:17 Accept: TCP{192.168.111.4:1883 > 192.168.111.51:59824} 48 ok out
2021/09/22 15:29:27 Accept: ICMPv4{100.78.123.82:0 > 192.168.111.18:0} 84 ok out
2021/09/22 15:29:37 Accept: TCP{192.168.111.4:1883 > 192.168.111.51:53771} 48 ok out
2021/09/22 15:29:42 open-conn-track: timeout opening (TCP 100.78.123.82:53442 => 192.168.111.170:6053) to node [7imlJ]; online=yes, lastRecv=3s
2021/09/22 15:29:43 open-conn-track: timeout opening (TCP 100.78.123.82:55900 => 192.168.111.166:6053) to node [7imlJ]; online=yes, lastRecv=5s
2021/09/22 15:29:47 Accept: TCP{192.168.111.4:1883 > 192.168.111.56:60857} 48 ok out
2021/09/22 15:29:57 Accept: TCP{192.168.111.4:58190 > 192.168.111.169:6053} 40 ok out
2021/09/22 15:30:04 open-conn-track: flow TCP (TCP 100.78.123.82:39532 => 192.168.111.53:6053) got RST by peer
2021/09/22 15:30:05 open-conn-track: timeout opening (TCP 100.78.123.82:59688 => 192.168.111.160:6668) to node [7imlJ]; online=yes, lastRecv=7s
2021/09/22 15:30:05 open-conn-track: timeout opening (TCP 100.78.123.82:43758 => 192.168.111.159:6668) to node [7imlJ]; online=yes, lastRecv=7s
2021/09/22 15:30:05 open-conn-track: timeout opening (TCP 100.78.123.82:38714 => 192.168.111.158:6668) to node [7imlJ]; online=yes, lastRecv=7s
2021/09/22 15:30:05 open-conn-track: timeout opening (TCP 100.78.123.82:34400 => 192.168.111.156:6668) to node [7imlJ]; online=yes, lastRecv=7s
2021/09/22 15:30:07 Accept: ICMPv4{100.78.123.82:0 > 192.168.111.18:0} 84 ok out
2021/09/22 15:30:17 Accept: ICMPv4{100.78.123.82:0 > 192.168.111.18:0} 84 ok out
2021/09/22 15:30:27 Accept: TCP{192.168.111.4:1883 > 192.168.111.55:57828} 52 ok out
2021/09/22 15:30:37 Accept: ICMPv4{100.78.123.82:0 > 192.168.111.18:0} 84 ok out
2021/09/22 15:30:45 open-conn-track: timeout opening (TCP 100.78.123.82:53520 => 192.168.111.170:6053) to node [7imlJ]; online=yes, lastRecv=6s
2021/09/22 15:30:46 open-conn-track: timeout opening (TCP 100.78.123.82:55978 => 192.168.111.166:6053) to node [7imlJ]; online=yes, lastRecv=8s
2021/09/22 15:30:47 Accept: TCP{192.168.111.4:1883 > 192.168.111.51:62604} 48 ok out
