### ISSUE TITLE
Allow for port forward.

### ISSUE THREAD

**Issue by thomasjohansen** [hassio-addons/addon-tailscale#318]
# Problem/Motivation
When tailscale is behind NAT it will automatically use a DERP server to do the NAT traversal. 

This can be avoided by allowing port 41641.

More about it here: https://tailscale.com/kb/1082/firewall-ports

When using a DERP server, the troughtput often is less than 1MB/s.

## Proposed changes
Configure the Docker image to expose port 41641.

**Comment by sinclairpaul** [comment]
The addon runs on the host network, there shouldn't be any ports to expose.

**Comment by thomasjohansen** [comment]
I've tried to setup port forwarding without luck. What worked was NAT-PMP. I'll close for now.
