### ISSUE TITLE
Can't access HA's network

### ISSUE THREAD

**Issue by janosrusiczki** [hassio-addons/addon-tailscale#32]
# Problem/Motivation

Can't access HA's network from another location.

## Expected behavior

I want to be able to access machines on HA's network from another location / my mobile phone.

## Actual behavior

I can't access machines on HA's network from another location / my mobile phone.

## Steps to reproduce

I have HA running on a RPi at another location on a "standard" network with 192.168.1.x type addresses - the RPi's IP address is 192.168.1.70. I have installed the Tailscale addon on it, logged in, went on the Tailscale site and enabled subnet routes.

![image](https://user-images.githubusercontent.com/189468/134816499-53b311ff-a08f-466e-8164-806da81b1711.png)

However, it gives me the error "Unable to relay traffic - This machine has IP forwarding disabled and cannot relay traffic. Please enable IP forwarding on this machine to use relay features like subnets or exit nodes."

From my current location I'm connecting to Tailscale and if I try to access the Tailscale HA IP at port 8123 it works. If I try and access the HA's IP address (192.168.1.70:8123) it works. But if I try any other address on the network at the other location it doesn't work.

As an example, if I try to access http://192.168.1.71 on the other network, which is a Tasmota switch, in HA's Tailscale log I see: 

`2021/09/26 19:48:23 Accept: TCP{red.act.ed.add:53621 > 192.168.1.71:80} 52 tcp ok`

But nothing more happens.

Isn't this the whole purpose of VPN? Am I doing something wrong?

**Comment by SiM22** [comment]
I have had these issues on other linux distros and home assistant, there is an issue I opened on the tailscale side. It is still not fixed and it is quite a bad bug to have. It involves the normal --accept-routes flag - https://github.com/tailscale/tailscale/issues/1164

I just uninstalled tailscale on the devices it does this and will not use tailscale on these affected devices anymore until they fix this bug.
