### ISSUE TITLE
Tailscale homeassistant addon (hassio) not supporting debian

### ISSUE THREAD

**Issue by haklai** [hassio-addons/addon-tailscale#325]
# Problem/Motivation

> when enabling "Accept routes" mode, it is looking for kernel config at /proc/config.gz (according to logs) which is not available on Debian. Then fails to start.

From log:
[09:49:37] INFO: Clamping the MSS to the MTU for all advertised subnet's interface,
[09:49:37] INFO: to support site-to-site networking better
zcat: /proc/config.gz: No such file or directory
[09:49:37] WARNING: Altering the MSS is not supported due to missing kernel module,
[09:49:37] WARNING: skip clamping the MSS to the MTU for all advertised subnet's interface

https://wiki.debian.org/KernelFAQ :
Does Debian have /proc/config.gz?
/proc/config.gz isn't available in Debian, because the config is provided in /boot/config-*, no need for the in-memory variant (Kernel configuration CONFIG_IKCONFIG and CONFIG_IKCONFIG_PROC).

## Expected behavior

> "Accept routes" mode should work

## Actual behavior

> Tailscale addon wont start when configured for "Accept routes" on Debian

s6-rc: info: service protect-subnets successfully stopped
[09:49:37] INFO: Service Tailscale web exited with code 256 (by signal 15)
s6-rc: info: service web successfully stopped
2024/02/02 09:49:37 flushing log.
2024/02/02 09:49:37 logger closing down
[09:49:38] INFO: Service tailscaled exited with code 0 (by signal 0)

## Steps to reproduce

> Follow https://www.home-assistant.io/installation/linux#install-home-assistant-supervised
Install tailscale addon
Configure "Accept routes"

My config:
accept_routes: true
userspace_networking: false

## Proposed changes

> Dont rely on /proc/config.gz for fetching kernel config as its availability is disto dependent

**Comment by lmagyar** [comment]
I made a quick fix for this. Tested the changes on Ubuntu manually, not on a real Supervised installation.

You can test it by stopping and disabling auto-start of the official add-on, installing my fork from https://github.com/lmagyar/homeassistant-addon-tailscale, copy-paste the YAML settings from the official add-on to the forked add-on, start and login to tailnet with the forked add-on.

**Comment by haklai** [comment]
Thanks for quick response on this one!

However, It is still not solved on Debian :(

Now I'm getting on my supervised installation:

[22:46:47] INFO: Clamping the MSS to the MTU for all advertised subnet's interface,
[22:46:47] INFO: to support site-to-site networking better
cat: /boot/config-6.1.0-17-amd64: No such file or directory
[22:46:47] WARNING: Altering the MSS is not supported due to missing kernel module,
[22:46:47] WARNING: skip clamping the MSS to the MTU for all advertised subnet's interface

Thanks,
Nadav

**Comment by lmagyar** [comment]
Gosh, what does it say? `ls -l /boot/config-*`

**Comment by haklai** [comment]
on host brings:

ls -l /boot/config-*
-rw-r--r-- 1 root root 259602 Sep  7 03:39 /boot/config-6.1.0-12-amd64
-rw-r--r-- 1 root root 259421 Sep 29 00:15 /boot/config-6.1.0-13-amd64
-rw-r--r-- 1 root root 259455 Dec 12 07:16 /boot/config-6.1.0-16-amd64
-rw-r--r-- 1 root root 259420 Dec 30 04:31 /boot/config-6.1.0-17-amd64

However, inside one of the home assistant dockers it brings nothing:
ls -l /boot/config-*
ls: /boot/config-*: No such file or directory

**Comment by home-ctrl** [comment]
Can we please reopen this ticket?

**Comment by haklai** [comment]
I propose the following change as a workaround since unlike /proc, the /boot folder is not mounted in the docker rootfs.
With this change, you can manually copy the kernel config file from /boot folder to the local persistent data folder of the addon and it will be properly detected. Tested locally.

diff --git a/tailscale/rootfs/usr/bin/kernel-config b/tailscale/rootfs/usr/bin/kernel-config
index 75d6022..7d3623f 100755
--- a/tailscale/rootfs/usr/bin/kernel-config
+++ b/tailscale/rootfs/usr/bin/kernel-config
@@ -3,5 +3,5 @@
 if bashio::fs.file_exists /proc/config.gz; then
   zcat /proc/config.gz
 else
-  cat /boot/config-$(uname -r)
+  cat /data/config-$(uname -r)
 fi

**Comment by lmagyar** [comment]
Sorry for my slow response (my dev environment is in ruins).

I think it would be better to remove these kernel config checks altogether.
- It was placed there mainly because some of the HA OS images had different routing capabilities, but it was already fixed by the OS team (see https://github.com/home-assistant/operating-system/issues/3026 and https://github.com/home-assistant/operating-system/pull/3027).
- The other kernel config check is TCPMSS related, but that results only in a warning, so we can test whether that TCPMSS manipulation fails and emit a warning then, and do not check the kernel config in advance.

***So could you please check*** on your Debian/Supervised what it says: `cat /boot/config-$(uname -r) | grep -E '^CONFIG_IP_MULTIPLE_TABLES=|^CONFIG_IPV6_MULTIPLE_TABLES=|^CONFIG_NETFILTER_XT_TARGET_TCPMSS='`

**Comment by haklai** [comment]
I agree. if not a must better remove those checks. anyway the feature will fail to work if those modules are not available.

On my system:
cat /boot/config-$(uname -r) | grep -E '^CONFIG_IP_MULTIPLE_TABLES=|^CONFIG_IPV6_MULTIPLE_TABLES=|^CONFIG_NETFILTER_XT_TARGET_TCPMSS='
CONFIG_IP_MULTIPLE_TABLES=y
CONFIG_IPV6_MULTIPLE_TABLES=y
CONFIG_NETFILTER_XT_TARGET_TCPMSS=m

I can also confirm the feature is working with the hack i proposed in previous comment.

**Comment by lmagyar** [comment]
After the new fix is released, do not forget to delete your /data/config-xxxx file, the /data folder is part of the backup, and this config file is unnecessary to be there for eternity.

**Comment by haklai** [comment]
Will do! Thanks a lot for the help on this matter!
