### ISSUE TITLE
can't reauthenticate after upgrading to  0.16.0

### ISSUE THREAD

**Issue by grayfrost90** [hassio-addons/addon-tailscale#333]
# Problem/Motivation

After upgrading to 0.16.0, tailscale reauthentication isn't working - clicking the button doesn't do anything noticable.

## Expected behavior

Clicking reauthenticate would prompt to log into tailscale

## Actual behavior

nothing

## Steps to reproduce

upgrade to  0.16.0

**Troubleshooting notes**

I've tried uninstalling the client and deleting the machine from tailscale admin, but the problem still exists. logs on the addon are showing:

```
2024/02/20 21:58:04 control: LoginInteractive -> regen=true
2024/02/20 21:58:04 control: doLogin(regen=true, hasUrl=false)
2024/02/20 21:58:04 Received error: fetch control key: Get "https://controlplane.tailscale.com/key?v=87": remote error: tls: handshake failure
```

**Comment by lmagyar** [comment]
Strange, I doesn't even have a reauthenticate button. Tested with key expiry enabled and disabled.
"Reauth" works this way: delete machine from the admin console, restart add-on, authenticate on the WEB UI.
Did your key expired? Any time I tested this situation, it was a total mess and I gave up and reinstalled the add-on and disabled key expiry.

**Comment by grayfrost90** [comment]
I had key expiry disabled, but now I don't even have the machine in the admin console so I would assume it should behave like a new client. It's almost like it's remembered the settings even after deleting the add on. I enabled debug logs but there wasn't much more to go on

**Comment by lmagyar** [comment]
Uninstalling the add-on deletes everything, after a fresh new install it won't/can't remember anything.
What is your installation type? VM, Supervised, HA OS on real hardware?
Yeah, debug log means it won't truncate the log after 200 lines, but it doesn't mean more details, Tailscale is quite chatty by default. Normally you don't need the messages after it successfully started.

**Comment by grayfrost90** [comment]
I'm running HA OS on an RPi4. I thought it could have had something to do with Nginx proxy manager running as well - only because I saw a similar issue on the tailscale GitHub and references to Nginx in the logs... But stopping that makes no difference either. It must be failing to contact the tailscale servers. I'll have more of a play tonight with the setup and see how far I get.

Is there anything useful I can get out of it to help troubleshoot??
