### ISSUE TITLE
Upgraded to 2024.3.0 and tailscale doesn't recognize if it's running

### ISSUE THREAD

**Issue by dmz006** [hassio-addons/addon-tailscale#337]
# Problem/Motivation

Upgraded to 2024.3.0 and tailscale now does not recognize it is running. Logs show it running, I can see it on the network, access and ping it; but the HA interface does not see it running.

I uninstalled and reinstalled tailscale which is at version 0.16.0
## Expected behavior

Status page and side panel page should work

## Actual behavior

Does not show it started in status page and side panel page doesn't load because HA thinks it is not running

## Steps to reproduce

Upgrade to 2024.3.0, install tailscale, test

## Proposed changes

Here are the logs of my system
![image](https://github.com/hassio-addons/addon-tailscale/assets/548875/14750a11-4534-4181-a317-994dea23afc9)
![image](https://github.com/hassio-addons/addon-tailscale/assets/548875/4b54ffdf-fb11-4abf-82e4-29ffff996997)

2024/03/07 12:17:15 control: RegisterReq: onode= node=[a06Qh] fup=true nks=false
2024/03/07 12:17:15 control: RegisterReq: got response; nodeKeyExpired=false, machineAuthorized=true; authURL=false
2024/03/07 12:17:15 blockEngineUpdates(false)
2024/03/07 12:17:16 active login: dmz
2024/03/07 12:17:16 Switching ipn state NeedsLogin -> Starting (WantRunning=true, nm=true)
2024/03/07 12:17:16 magicsock: SetPrivateKey called (init)
2024/03/07 12:17:16 wgengine: Reconfig: configuring userspace WireGuard config (with 0/9 peers)
2024/03/07 12:17:16 wgengine: Reconfig: configuring router
2024/03/07 12:17:16 monitor: gateway and self IP changed: gw=GWIP self=HAIP
2024/03/07 12:17:16 wgengine: Reconfig: configuring DNS
2024/03/07 12:17:16 dns: Set: {DefaultResolvers:[1.1.1.1] Routes:{HOSTS:[]}+65arpa SearchDomains:[DOMAIN] Hosts:11}
2024/03/07 12:17:16 dns: Resolvercfg: {Routes:{.:[1.1.1.1]} Hosts:11 LocalDomains:[LOCALHOSTS]+65arpa}
2024/03/07 12:17:16 dns: OScfg: {Nameservers:[100.100.100.100] SearchDomains:[SEARCHDOMAIN] }
2024/03/07 12:17:16 rename of "/etc/resolv.conf" to "/etc/resolv.pre-tailscale-backup.conf" failed (rename /etc/resolv.conf /etc/resolv.pre-tailscale-backup.conf: device or resource busy), falling back to copy+delete
2024/03/07 12:17:16 peerapi: serving on http://100.64.0.11:36186
2024/03/07 12:17:16 peerapi: serving on http://[fd7a:115c:a1e0::b]:32922
2024/03/07 12:17:16 magicsock: home is now derp-1 (nyc)
2024/03/07 12:17:16 magicsock: adding connection to derp-1 for home-keep-alive
2024/03/07 12:17:16 magicsock: 1 active derp conns: derp-1=cr0s,wr0s
2024/03/07 12:17:16 Switching ipn state Starting -> Running (WantRunning=true, nm=true)
Success.
2024/03/07 12:17:16 control: NetInfo: NetInfo{varies=false hairpin=false ipv6=false ipv6os=true udp=true icmpv4=false derp=#1 portmap= link="" firewallmode="ipt-default"}
Some peers are advertising routes but --accept-routes is false
2024/03/07 12:17:16 derphttp.Client.Connect: connecting to derp-1 (nyc)
[12:17:16] INFO: Tailscale is running
2024/03/07 12:17:16 magicsock: endpoints changed: ENDPOINT:47993 (stun), 172.30.32.1:47993 (local), 172.30.232.1:47993 (local), LOCALIP:47993 (local)
2024/03/07 12:17:17 magicsock: derp-1 connected; connGen=1
s6-rc: info: service post-tailscaled successfully started
s6-rc: info: service mss-clamping: starting
[12:17:17] INFO: Clamping the MSS to the MTU for all advertised subnet's interface,
[12:17:17] INFO: to support site-to-site networking better
[12:17:17] INFO:   Clamping the MSS for interface enp2s1 (IPv4)
[12:17:17] INFO:   Clamping the MSS for interface enp2s1 (IPv6)
s6-rc: info: service mss-clamping successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
2024/03/07 12:17:17 health("overall"): ok
2024/03/07 12:17:56 wgengine: idle peer [8pCZn] now active, reconfiguring WireGuard
2024/03/07 12:17:56 wgengine: Reconfig: configuring userspace WireGuard config (with 1/9 peers)
2024/03/07 12:17:56 magicsock: disco: node [8pCZn] d:563513ee86d9274a now using MYIP:41641 mtu=1360 tx=ff60e6e127f4
2024/03/07 12:17:56 Accept: ICMPv4{100.64.0.1:0 > 100.64.0.11:0} 84 icmp ok
2024/03/07 12:17:56 Accept: ICMPv4{100.64.0.11:0 > 100.64.0.1:0} 84 ok out
2024/03/07 12:17:57 Accept: ICMPv4{100.64.0.1:0 > 100.64.0.11:0} 84 icmp ok
2024/03/07 12:18:06 Accept: TCP{100.64.0.1:36236 > 100.64.0.11:8123} 83 tcp non-syn
2024/03/07 12:18:20 Accept: TCP{100.64.0.11:8123 > 100.64.0.1:36236} 803 ok out
2024/03/07 12:18:22 wgengine: idle peer [G1hsP] now active, reconfiguring WireGuard
2024/03/07 12:18:22 wgengine: Reconfig: configuring userspace WireGuard config (with 2/9 peers)
2024/03/07 12:18:22 magicsock: disco: node [G1hsP] d:ee9f5512b753fc1b now using OTHERIP:51935 mtu=1360 tx=3e787877934e
2024/03/07 12:18:29 Accept: TCP{100.64.0.1:36236 > 100.64.0.11:8123} 68 tcp non-syn
2024/03/07 12:18:41 Accept: TCP{100.64.0.11:8123 > 100.64.0.1:36236} 1280 ok out
2024/03/07 12:18:49 Accept: TCP{100.64.0.11:8123 > 100.64.0.1:36236} 548 ok out
2024/03/07 12:19:00 Accept: TCP{100.64.0.11:8123 > 100.64.0.1:36236} 351 ok out
2024/03/07 12:19:07 Accept: TCP{100.64.0.1:36236 > 100.64.0.11:8123} 66 tcp non-syn
2024/03/07 12:19:16 Accept: TCP{100.64.0.11:8123 > 100.64.0.1:36236} 754 ok out
2024/03/07 12:19:29 Accept: TCP{100.64.0.1:36236 > 100.64.0.11:8123} 65 tcp non-syn
2024/03/07 12:19:37 Accept: TCP{100.64.0.11:8123 > 100.64.0.10:35558} 52 ok out
2024/03/07 12:19:37 magicsock: adding connection to derp-9 for [G1hsP]
2024/03/07 12:19:37 magicsock: 2 active derp conns: derp-1=cr2m0s,wr1m0s derp-9=cr0s,wr0s
2024/03/07 12:19:37 derphttp.Client.Recv: connecting to derp-9 (dfw)
2024/03/07 12:19:37 magicsock: derp-9 connected; connGen=1
2024/03/07 12:19:50 Accept: TCP{100.64.0.11:8123 > 100.64.0.1:36236} 791 ok out
2024/03/07 12:19:57 Accept: TCP{100.64.0.1:36222 > 100.64.0.11:8123} 52 tcp non-syn
2024/03/07 12:20:07 Accept: TCP{100.64.0.1:36236 > 100.64.0.11:8123} 66 tcp non-syn
2024/03/07 12:20:19 Accept: TCP{100.64.0.1:36236 > 100.64.0.11:8123} 66 tcp non-syn
2024/03/07 12:20:26 Accept: TCP{100.64.0.1:36236 > 100.64.0.11:8123} 69 tcp non-syn
2024/03/07 12:20:37 magicsock: closing connection to derp-9 (idle), age 1m0s
2024/03/07 12:20:37 magicsock: 1 active derp conns: derp-1=cr3m0s,wr2m0s
2024/03/07 12:20:45 Accept: TCP{100.64.0.1:36236 > 100.64.0.11:8123} 93 tcp non-syn
2024/03/07 12:20:48 Accept: TCP{100.64.0.11:8123 > 100.64.0.1:36236} 271 ok out
2024/03/07 12:21:00 Accept: TCP{100.64.0.11:8123 > 100.64.0.1:36236} 359 ok out
2024/03/07 12:21:07 Accept: TCP{100.64.0.1:36236 > 100.64.0.11:8123} 81 tcp non-syn
2024/03/07 12:21:16 Accept: TCP{100.64.0.11:8123 > 100.64.0.1:36236} 1280 ok out
2024/03/07 12:21:26 Accept: TCP{100.64.0.1:36236 > 100.64.0.11:8123} 67 tcp non-syn
2024/03/07 12:21:39 Accept: TCP{100.64.0.11:8123 > 100.64.0.1:36236} 304 ok out
2024/03/07 12:21:46 Accept: TCP{100.64.0.11:8123 > 100.64.0.1:36236} 278 ok out
2024/03/07 12:21:56 Accept: TCP{100.64.0.1:36222 > 100.64.0.11:8123} 52 tcp non-syn
2024/03/07 12:22:10 Accept: TCP{100.64.0.1:36236 > 100.64.0.11:8123} 69 tcp non-syn
2024/03/07 12:22:17 Accept: TCP{100.64.0.1:36236 > 100.64.0.11:8123} 70 tcp non-syn
2024/03/07 12:22:30 Accept: TCP{100.64.0.11:8123 > 100.64.0.1:55552} 52 ok out
2024/03/07 12:22:40 Accept: TCP{100.64.0.1:56076 > 100.64.0.11:8123} 60 tcp ok
2024/03/07 12:22:46 Accept: TCP{100.64.0.11:8123 > 100.64.0.1:36236} 273 ok out
2024/03/07 12:22:56 Accept: TCP{100.64.0.1:56078 > 100.64.0.11:8123} 1280 tcp non-syn
2024/03/07 12:23:06 Accept: TCP{100.64.0.11:8123 > 100.64.0.1:36236} 499 ok out
2024/03/07 12:23:16 Accept: TCP{100.64.0.11:8123 > 100.64.0.1:36236} 384 ok out
2024/03/07 12:23:22 magicsock: adding connection to derp-9 for [G1hsP]
2024/03/07 12:23:22 magicsock: 2 active derp conns: derp-1=cr6m0s,wr5m0s derp-9=cr0s,wr0s
2024/03/07 12:23:22 derphttp.Client.Recv: connecting to derp-9 (dfw)
2024/03/07 12:23:22 magicsock: derp-9 connected; connGen=1
2024/03/07 12:23:45 Accept: TCP{100.64.0.1:56076 > 100.64.0.11:8123} 52 tcp non-syn
2024/03/07 12:23:45 Accept: TCP{100.64.0.1:50672 > 100.64.0.11:8123} 52 tcp non-syn
2024/03/07 12:23:50 Accept: TCP{100.64.0.11:8123 > 100.64.0.1:36236} 356 ok out
2024/03/07 12:24:00 Accept: TCP{100.64.0.11:8123 > 100.64.0.1:36236} 340 ok out
2024/03/07 12:24:14 Accept: TCP{100.64.0.11:8123 > 100.64.0.1:56076} 52 ok out
2024/03/07 12:24:20 Accept: TCP{100.64.0.11:8123 > 100.64.0.1:36236} 357 ok out
2024/03/07 12:24:22 magicsock: closing connection to derp-9 (idle), age 1m0s
2024/03/07 12:24:22 magicsock: 1 active derp conns: derp-1=cr7m0s,wr6m0s
2024/03/07 12:24:42 Accept: TCP{100.64.0.10:35571 > 100.64.0.11:8123} 60 tcp ok
2024/03/07 12:24:42 Accept: TCP{100.64.0.11:8123 > 100.64.0.10:35571} 60 ok out
2024/03/07 12:24:42 magicsock: adding connection to derp-16 for [G1hsP]
[further tailscaled logs suppressed, set add-on's configuration option 'log_level' to 'debug' to see further tailscaled logs]

**Comment by lmagyar** [comment]
I've tried to reproduce this, but I can't. This seems to be a HA Frontend or maybe Supervisor issue, but nothing similar is reported there. I suggest to restart the HA device, meanwhile clear all site specific browser cache/cookies, and retry testing the issue.
