### ISSUE TITLE
Update to Tailscale 1.66.1

### ISSUE THREAD

**Issue by phipolis** [hassio-addons/addon-tailscale#353]
# Problem/Motivation

Tailscale versions before 1.66.0 are impacted by [security bulletin ts-2024-005](https://tailscale.com/security-bulletins#ts-2024-005), and [their guidance](https://tailscale.com/changelog#2024-05-08) is "We recommend updating all Tailscale clients to v1.66.0 or later to benefit from additional security improvements." 

## Proposed changes

Requesting a new release of `addon-tailscale`  that includes the latest upstream version.

**Comment by frenck** [comment]
Was fixed in #352

**Comment by phipolis** [comment]
I just missed that. Cheers!
