### ISSUE TITLE
Security update of upstream tailscale available - update to tailscale 1.66.3 (or newer)

### ISSUE THREAD

**Issue by robinsmidsrod** [hassio-addons/addon-tailscale#355]
# Problem/Motivation

I'm getting this information for my Home Assistant OS installation in my Tailscale management panel:

>This machine is running a version with a known security vulnerability. It’s recommended to update to 1.66.3.
Follow [these instructions](https://tailscale.com/kb/1067/update/?tab=linux) to update this machine.

## Expected behavior

Running the latest non-vulnerable version.

## Actual behavior

Still running version 1.64.0 (which is vulnerable).

## Steps to reproduce

Just use latest version of addon. At the time of filing this bug is 0.18.0.

## Proposed changes

We should always be running software where known security issues are fixed.

**Comment by frenck** [comment]
Resolved in #354
