### ISSUE TITLE
tailscale update to 1.66. When? Ref. Security-bulletins#ts-2024-005

### ISSUE THREAD

**Issue by rudydevolder** [hassio-addons/addon-tailscale#359]
# Problem/Motivation
as described in [https://tailscale.com/security-bulletins#ts-2024-005](
)
Devices outside of the tailnet, but on the same LAN as an exit node, subnet router, or app connector could connect to ports on tailnet nodes that are allowed by ACLs.

**Comment by frenck** [comment]
Merged in #354

**Comment by recursiveGecko** [comment]
There's no update available in HA. Do you still need to tag a release in this repository before it becomes available?

**Comment by frenck** [comment]
Yup. Stuff doing ship itself.
