### ISSUE TITLE
Failure with Tailscale integration and DNS resolving

### ISSUE THREAD

**Issue by kernelb00t** [hassio-addons/addon-tailscale#376]
With latest versions of HA, HAOS, HACS and this addon, in a Proxmox VE server, the Tailscale addon with user space networking disabled can't set itself as the DNS resolver for at least the tailnet's domain. It seems that Tailscale and network manager never talks between them from what I can see in `/etc/resolv.conf` within the `Terminal & SSH` addon. I can access HA through Tailscale but HA can't resolve any address of the tailnet. For example, I can't connect to the NUT server running on the Proxmox host via Tailscale, whereas on my computer I can contact and retrieve information from it.

Expected behaviour :
When on HA Cli, after typing `login`, ping `proxmox.my-tailnet.ts.net`. The command has no errors.
When in the Terminal addon, try to ping the same host. The command should work.
When setting up an integration/addon, putting a Tailscale domain or IP address should cause no errors.

When I was in my logs, I saw that Tailscale couldn't rename the /etc/resolv.conf file to /etc/resolve.pre-tailscale.conf (or a name like that), due to the file system being RO. I was not able to make a screenshot/copy the logs.

**Comment by lmagyar** [comment]
See #310 TLDR: accessing with IPs work, DNS resolving needs some workaround :/

**Comment by bhovig** [comment]
Same problem.  Workaround:

At the home assistant cli:

ha dns options --servers dns://100.100.100.100
ha dns restart

dns now resolves Tailscale ips when Tailscale addon is active.

**Comment by sinclairpaul** [comment]
> Same problem. Workaround:

It's not a workaround, the container can't influence the base OS configuration.  You can also set the DNS settings via the UI.

In my opinion this should be closed out, if you want to run Tailscale in a container this is a limitation of it.

**Comment by bjeanes** [comment]
I'm also experiencing this, bot

**Comment by bjeanes** [comment]
> Same problem. Workaround:
> 
> At the home assistant cli:
> 
> ha dns options --servers dns://100.100.100.100 ha dns restart
> 
> dns now resolves Tailscale ips when Tailscale addon is active.

Apparently at the cost of resolving anything else, though.

**Comment by kernelb00t** [comment]
> > Same problem. Workaround:
> > 
> > At the home assistant cli:
> > 
> > ha dns options --servers dns://100.100.100.100 ha dns restart
> > 
> > dns now resolves Tailscale ips when Tailscale addon is active.
> 
> Apparently at the cost of resolving anything else, though.

It shouldn't, though. The tailscale DNS is the "first" DNS, so everything will be resolved using it. If you try to resolve a non-Tailscale domain, it will use the tailnet's default global DNS.
![Capture d’écran du 2024-07-22 07-46-07.png](https://github.com/user-attachments/assets/c518d674-0392-4399-bc32-5d18a0424d88)

**Comment by kernelb00t** [comment]
You have to put your connection in static (Settings>System>Network>Configure>IPv4>Static> Set DNS to 100.100.100.100). It's not very good, but since HA's CoreDNS is uncustomizable at all we can't really do anything better. Then, it should work good.

If not, reset your DNS config (ha dns reset), then redo this ↑

**Comment by lmagyar** [comment]
Thanks for the reply, I've already tried those steps several times, it has never worked. I try to config TS DNS as default DNS for HA few times a year, maybe it will work once, currently it doesn't work on any of my configs. I clearly miss a step somewhere, but can't figure out what. I gave up again.

**Comment by kernelb00t** [comment]
Sorry, I am unable to check if it's still happening, I don't have for this now. But I don't think this issue is resolved as nobody mentioned it in a PR.
