### ISSUE TITLE
Problem with "ethtool" on 0.19.1

### ISSUE THREAD

**Issue by ThierryPanam** [hassio-addons/addon-tailscale#377]
Hello,

Tailscale 0.18.0 worked perfectly.
Migration to 0.19.1 addon and something seems wrong with "ethtool". So tailscale service is not running.

Thanks

-----------------------------------------------------------
 Add-on: Tailscale
 Zero config VPN for building secure networks
-----------------------------------------------------------
 Add-on version: 0.19.1
 You are running the latest version of this add-on.
 System: Debian GNU/Linux 11 (bullseye)  (aarch64 / qemuarm-64)
 Home Assistant Core: 2024.6.0
 Home Assistant Supervisor: 2024.06.0
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
s6-rc: info: service base-addon-banner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service base-addon-log-level: starting
s6-rc: info: service fix-attrs successfully started
Log level is set to DEBUG
s6-rc: info: service base-addon-log-level successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service init-nginx: starting
s6-rc: info: service web: starting
s6-rc: info: service tailscaled: starting
s6-rc: info: service web successfully started
s6-rc: info: service tailscaled successfully started
s6-rc: info: service post-tailscaled: starting
[19:08:23] INFO: Starting Tailscale web...
[19:08:23] INFO: Starting Tailscale...
[19:08:23] INFO: Allow UDP GRO for forwarding on eth0
**ethtool: bad command line argument(s)
For more information run ethtool -h
s6-rc: warning: unable to start service post-tailscaled: command exited 1**
2024/06/06 19:08:23 logtail started
2024/06/06 19:08:23 Program starting: v1.66.4-t067defc64-g49481b7d0, Go 1.22.3: []string{"/opt/tailscaled", "--state=/data/tailscaled.state", "--statedir=/data/state", "--tun=userspace-networking"}
2024/06/06 19:08:23 LogID: 883ae260fc2801adcd291983a8755c19bf075af69154ab1937ecf8fcee17b2a5
2024/06/06 19:08:23 logpolicy: using system state directory "/var/lib/tailscale"
logpolicy.ConfigFromFile /var/lib/tailscale/tailscaled.log.conf: open /var/lib/tailscale/tailscaled.log.conf: no such file or directory
logpolicy.Config.Validate for /var/lib/tailscale/tailscaled.log.conf: config is nil
2024/06/06 19:08:23 dns: [resolved-ping=yes rc=unknown ret=direct]
2024/06/06 19:08:23 dns: using "direct" mode
2024/06/06 19:08:23 dns: using *dns.directManager
s6-rc: info: service init-nginx successfully started
s6-rc: info: service nginx: starting
2024/06/06 19:08:23 wgengine.NewUserspaceEngine(tun "userspace-networking") ...
2024/06/06 19:08:23 dns: using dns.noopManager
2024/06/06 19:08:23 link state: interfaces.State{defaultRoute=eth0 ifs={docker0:[172.17.0.1/16 llu6] eth0:[192.168.1.65/24 2a02:8428:483d:2801:e13:b343:f42d:eee2/64 llu6] hassio:[172.30.32.1/23 llu6]} v4=true v6=true}
2024/06/06 19:08:23 onPortUpdate(port=53864, network=udp6)
2024/06/06 19:08:23 onPortUpdate(port=45657, network=udp4)
s6-rc: info: service nginx successfully started
2024/06/06 19:08:23 magicsock: disco key = d:4384e1e21a0c9428
2024/06/06 19:08:23 Creating WireGuard device...
2024/06/06 19:08:23 Bringing WireGuard device up...
2024/06/06 19:08:23 Bringing router up...
2024/06/06 19:08:23 Clearing router settings...
2024/06/06 19:08:23 Starting network monitor...
2024/06/06 19:08:23 Engine created.
/run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.
/run/s6/basedir/scripts/rc.init: fatal: stopping the container.
2024/06/06 19:08:23 pm: using backend prefs for "profile-e22d": Prefs{ra=true dns=true want=true webclient=true routes=[0.0.0.0/0 ::/0 192.168.1.0/24] snat=true statefulFiltering=false nf=on host="Khadas" update=check Persist{lm=, o=, n=[myGSl] u="ThierryPanam@github"}}
2024/06/06 19:08:23 logpolicy: using system state directory "/var/lib/tailscale"
s6-rc: info: service nginx: stopping
s6-rc: info: service tailscaled: stopping
2024/06/06 19:08:23 got LocalBackend in 46ms
2024/06/06 19:08:23 Start
2024/06/06 19:08:23 tailscaled got signal terminated; shutting down
2024/06/06 19:08:23 flushing log.
2024/06/06 19:08:23 logger closing down
[19:08:23] INFO: Service NGINX exited with code 256 (by signal 15)
s6-rc: info: service nginx successfully stopped
s6-rc: info: service init-nginx: stopping
s6-rc: info: service web: stopping
s6-rc: info: service init-nginx successfully stopped
[19:08:23] INFO: Service tailscaled exited with code 0 (by signal 0)
s6-rc: info: service tailscaled successfully stopped
[19:08:23] INFO: Service Tailscale web exited with code 256 (by signal 15)
s6-rc: info: service web successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service base-addon-log-level: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service base-addon-log-level successfully stopped
s6-rc: info: service base-addon-banner: stopping
s6-rc: info: service base-addon-banner successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped

**Comment by lmagyar** [comment]
Yes, it's fixed in #370, though not relesed yet. :(

**Comment by frenck** [comment]
It is scheduled for today/this weekend.
Busy week with the HA release.

**Comment by frenck** [comment]
Released: https://github.com/hassio-addons/addon-tailscale/releases/tag/v0.20.0
