### ISSUE TITLE
Subnet Routes not working with Headscale

### ISSUE THREAD

**Issue by mFabio98** [hassio-addons/addon-tailscale#384]
# Problem/Motivation

Subnet Routes not working with Headscale.

## Expected behavior

After specifying the subnet route in a '192.168.1.0/24' fashion, and accepting the subnet advertising server-side, the tailscale client should expose the subnet.

## Actual behavior

Instead of exposing to the tailnet the whole specified subnet, the addon manages to expose just the IP address of the home assistant machine.

## Steps to reproduce

It's quite involved. VPS running headscale, headscale-admin. Attached the log line I think is most relevant.

## Proposed changes

I'm not even remotely qualified to fill-in this field.

![image](https://github.com/hassio-addons/addon-tailscale/assets/100992233/4ccf09de-f0d3-4e41-9b68-51810c85162c)

**Comment by lmagyar** [comment]
Does this mean, that you can't access anything on the 192.168.1.0/24 subnet from your phone?

Note: The add-on basically sets the parameters of the TS cli, so if TS has any problem with Headscale, it seems to be a TS/HS issue.

**Comment by mFabio98** [comment]
I can access only the IP address of the machine running home assistant (IP 192.168.1.10, for example). Any other IP in the subnet is not accessible, including the gateway (192.168.1.1)

I've tried a few solutions and managed to resolve the issue by switching to a different addon (now i notice published by you @lmagyar):  https://github.com/lmagyar/homeassistant-addon-tailscale. With that it works as expected.

**Comment by lmagyar** [comment]
OK, good to know, then it really seems to be a TS issue: this "official" add-on is on TS v1.66.4, my add-on is on TS v1.68.1 - nearly all other stuff in these two add-ons are equivalent. A new release of this official add-on will fix this issue.

Note: In the past I've experimented with new features, some improvements, there were big differences, but nearly eg. got merged into this official add-on.

**Comment by mFabio98** [comment]
OK great, I can try again this 'official' addon once it gets updated to confirm whether the issue was solved or not. 
Many thanks for your support.
