### ISSUE TITLE
Exit node relay/direct connection

### ISSUE THREAD

**Issue by mcderd-coder** [hassio-addons/addon-tailscale#403]
I find that the exit node I have set up keeps reverting to a Relayed connection.

If I go into Home Assistant stop and start the Tailscale addon it will have a direct connection, but this does not last, so when it changes to a relayed connection the speed drops to under 1Mbps, with a direct connection it is 50-60 Mbps I have to stop and start the addon again.

Is there any way to make it have a direct connection all the time?

Thanks

**Comment by frenck** [comment]
Closing this. Release is expected soon. New base image and testing is left.

../Frenck

**Comment by mcderd-coder** [comment]
Thank you, I am quite new to this, when it is released will it show as an
update available in Home Assistant?

Regards Dennis

**Comment by lmagyar** [comment]
Yes. :)
