### ISSUE TITLE
Unable to Connect to Tailscale Nodes from Home Assistant OS in VM

### ISSUE THREAD

**Issue by lucius346346** [hassio-addons/addon-tailscale#427]
Description:
I cannot connect to other Tailscale nodes from my Home Assistant OS instance running in a virtual machine.

**Steps to Reproduce:**
- Install the Tailscale add-on in Home Assistant OS.
- Connect using the domain/name server to the Home Assistant web UI (this works fine).
- Attempt to ping or connect to other machines in the Tailscale network from Home Assistant OS.

**Expected Behavior:**
- I should be able to connect to other Tailscale nodes within the network.

**Actual Behavior:**
When I ping other Tailscale nodes, I receive a "bad address" error.

**What I Tried:**
Disabled the "Userspace networking mode" option.

**Environment:**
Home Assistant OS running in a virtual machine.
Tailscale add-on installed.

**Comment by lmagyar** [comment]
Did you try it with the IP addresses? That should work.

DNS requires additional steps to work. I think I will add that to the docs.

**Comment by lucius346346** [comment]
If I ping IP address it just hangs indefinitely (100% packet loss). Same thing happens when I use Home Assistant Tailscale IP itself.

**Comment by lmagyar** [comment]
Please check the add-on's config with the YAML view, do you really have that `userspace_networking: false` line? The HA add-on UI is broken, you click-clik-save-restart, but in reality you don't have this config line at the end. Though if you have, and you have the tailscale0 interfece on your host, it should work, I've tested it a few minutes ago with a vanilla HA VM + TS add-on config, and ping worked with IP.

**Comment by lucius346346** [comment]
OK, scratch that. IP does work, the addon just crashed. Thank you for the help!
