### ISSUE TITLE
Cannot access tailscale subnet with this addon

### ISSUE THREAD

**Issue by timoteofm** [hassio-addons/addon-tailscale#430]
I'm seeing this issue on my Home Assistant production environment. Just to make sure I made a new clean VM install.

Home Assistant OS 13.2 on VM Unraid 6.12.14.

The destination subnets are working fine, tried with 3 different devices on the same network. They can access this subnet.

Pinging destination 100.123.82.54 works fine but not the subnet 192.168.1.102.

Ok
![ping_tailscale](https://github.com/user-attachments/assets/6f028387-e226-494c-afa0-ac41b5f8bc7f)

Nok
![ping_tailscale2](https://github.com/user-attachments/assets/cf609c47-871e-43b3-bb88-b31bcc3b2341)

Configuration:
advertise_exit_node: false
advertise_connector: false
userspace_networking: false
snat_subnet_routes: false
accept_routes: true
accept_dns: true

**Comment by lmagyar** [comment]
What do you want to achieve???

Your local HA & TS runs on 192.168.1.x and you want to ping a machine on another TS's subnet in the same 192.168.1.x? It will never work. By default it will soft-brick your HA. We added quite elaborate workaround to not allow this.

What to do:
- Put one of your subnets on to a different domain, like 192.168.2.x.
- Enable it's subnet in the management web page of TS.
- First try it with snat_subnet_routes: true on both TS config. If it works and you absolutely know what is snat_subnet_routes and you need this and configured your network properly everywhere, then disable it.

**Comment by timoteofm** [comment]
I changed to a different subnets 192.168.2.x. Everything works fine.

I was strange because Unraid (with Tailscale) can ping a remote Tailscale within the same subnet. But not the HA addon. 

I prefer the HA addon because I don't want to accept_routes on my Unraid server.

Thank you for your help.

**Comment by lmagyar** [comment]
In theory it would be possible with the add-on also, if it wasn't "protecting" the whole local subnet (against Tailscale to route it to somewhere else), but only it's local IP. That would result in a quite strange situation where everything in the 192.168.1.x domain would go out to the other site, except HA's local IP. But what if you want to access something on the other site that has the same IP as your local HA? So finally the whole local subnet got the "protection" against Tailscale. It is a route table hack, that we put back the local subnets with a higher priority than Tailscale's routing, so we override what Tailscale wants. This is a multiyear long battle with Tailscale, see: https://github.com/tailscale/tailscale/issues/1227
