### ISSUE TITLE
Debian supervised Tailscaled 0.23.3 exited with code 1

### ISSUE THREAD

**Issue by shirou93** [hassio-addons/addon-tailscale#436]
# Problem/Motivation
Addon with disabled userspace network mode not starting.
> (Why the issue was filed)

## Expected behavior
Working addon with disable userspace
> (What you expected to happen)

## Actual behavior
After disable userspace adds exited with errors:

2024/12/07 17:22:05 wgengine.NewUserspaceEngine(tun "tailscale0") ...
2024/12/07 17:22:05 Linux kernel version: 6.1.0-28-amd64
2024/12/07 17:22:05 is CONFIG_TUN enabled in your kernel? `modprobe tun` failed with: modprobe: can't change directory to '/lib/modules': No such file or directory
2024/12/07 17:22:05 wgengine.NewUserspaceEngine(tun "tailscale0") error: tstun.New("tailscale0"): operation not permitted
2024/12/07 17:22:05 flushing log.
2024/12/07 17:22:05 logger closing down
2024/12/07 17:22:05 getLocalBackend error: createEngine: tstun.New("tailscale0"): operation not permitted
[17:22:05] INFO: Service tailscaled exited with code 1 (by signal 0)

> (What actually happened)

## Steps to reproduce
Install addon on supervised Debian HA and disable userspace option.
> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

Thanks for your work.

**Comment by frenck** [comment]
> 2024/12/07 17:22:05 is CONFIG_TUN enabled in your kernel? modprobe tun failed with: modprobe: can't change directory to '/lib/modules': No such file or directory

**Comment by shirou93** [comment]
On host
CONFIG_TUN=m

**Comment by shirou93** [comment]
It’s Debian issue after update. After add addon working fine.
echo "tun" | sudo tee -a /etc/modules 

Thanks
