### ISSUE TITLE
Support custom login server

### ISSUE THREAD

**Issue by poisonborz** [hassio-addons/addon-tailscale#438]
Please add support for self-hosted control servers (the --login-server attribute). A lot of people use entirely self-hosted tailscale networks.

https://tailscale.com/kb/1507/custom-control-server

In the docs / configuration there option is there, but it's not clear if and how this can be edited - if so, it would be nice to have it on the UI as well, or have a more visible description on how to edit it.

**Comment by frenck** [comment]
Done! 🚀 

https://github.com/hassio-addons/addon-tailscale/blob/main/tailscale/DOCS.md#option-login_server
