### ISSUE TITLE
0.3.0 and trusted_networks configuration not working

### ISSUE THREAD

**Issue by 2m** [hassio-addons/addon-tailscale#51]
# Problem

I am running a couple of Home Assistant instances that I use Tailscale to access. I have configured trusted network configuration provider to automatically login to HA whenever it is accessed from the Tailscale network:

```
auth_providers:
- type: trusted_networks
  trusted_networks:
  - 100.0.0.0/8
```

However since `0.3.0` this does not work anymore as Home Assistant sees that logins from Tailscale network are coming from the localhost address. To workaround it I added localhost to the trusted networks:

```
auth_providers:
- type: trusted_networks
  trusted_networks:
  - 127.0.0.1/32
  - 100.0.0.0/8
```

**Comment by frenck** [comment]
This is actually pretty much the expected behavior at this point and not a bug.

**Comment by 2m** [comment]
I see. Fair enough!
