### ISSUE TITLE
Allow Tags

### ISSUE THREAD

**Issue by kusold** [hassio-addons/addon-tailscale#53]
# Problem/Motivation
When you use ACLs, if you tag a device it loses the permissions of it's owner. This is useful if you want to prevent certain servers from talking to eachother, but still allow the owner (yourself) to talk to everything.

I have some machines that I do not want homeassistant to communicate with, and I'd like to manage this via tags. 

https://tailscale.com/kb/1068/acl-tags/

> (Why the issue was filed)

## Expected behavior

Your device shows up as tagged in the tailscale ui.

## Actual behavior

Tags are not an available configuration, so the device is owned as the user.

## Steps to reproduce

Install tailscale, view the device list and you'll see your username instead of a tag under the device.

## Proposed changes

Allow us to pass `--advertise-tags` to tailscale. If the option is modified, run `tailscale up` with the options.

**Comment by frenck** [comment]
I kinda dig the idea, but at the same time kinda enjoy the fact this add-on lives up to the tagline of Tailscale: Zero-conf VPN.

How about adding a single default tag to the add-on, e.g., `tag:homeassistant` ?

**Comment by kusold** [comment]
I appreciate the simplicity of that solution, but it might break existing setups.

When you add a tag to a device, it loses the ACL permissions of the owner which is desired for my use case, but deviates from the existing behavior. So if someone needs Home Assistant to talk to another Tailscale server, they would need to explicitly allow that via ACLs.

Additionally, the Tailscale UI will warn about a tag on a resource that doesn't exist in the ACLs.

**Comment by frenck** [comment]
You are right, that is not a good solution.

**Comment by kusold** [comment]
I was able to test this out and it worked great. Thank you for adding it.
