### ISSUE TITLE
Allow Accept Routes

### ISSUE THREAD

**Issue by kammerdiener** [hassio-addons/addon-tailscale#61]
# Problem/Motivation

In trying to provide some routing between various networks it would be nice for the add-on to allow me to accept routes so I don't have to send metrics over the open internet. 

## Expected behavior

Being able to bring up the plugin to Accept Routes from TailScale. 

## Proposed changes

Add the ability to accept routes from within HomeAssistant so that items can be sent over TailScale.

**Comment by frenck** [comment]
It accepts the routes on start, so a restart will work:

See: https://github.com/hassio-addons/addon-tailscale/blob/main/tailscale/rootfs/etc/services.d/tailscaled/post#L56

> Add the ability to accept routes from within HomeAssistant 

From within Home Assistant? If you mean as a switch in HA... This is not an integration. Add-ons don't provide entities.
