### ISSUE TITLE
Error pre-login, login screen not showing

### ISSUE THREAD

**Issue by bohtho** [hassio-addons/addon-tailscale#66]
# Problem/Motivation

Can't log in (and tailscale seems to not start correctly)

## Expected behavior

Expects login screen to keep loading and actually show up.

## Actual behavior

Black screen after clicking Log in and browser never finishes loading. Error in log.

> 2021/12/19 20:08:37 health("overall"): error: state=NeedsLogin, wantRunning=false
> 2021/12/19 20:08:37 wgengine: Reconfig: configuring userspace wireguard config (with 0/0 peers)
> 2021/12/19 20:08:37 wgengine: Reconfig: configuring router
> 2021/12/19 20:08:37 wgengine: Reconfig: configuring DNS
> 2021/12/19 20:08:37 dns: Set: {DefaultResolvers:[] Routes:{} SearchDomains:[] Hosts:0}
> 2021/12/19 20:08:37 dns: Resolvercfg: {Routes:{} Hosts:0 LocalDomains:[]}
> 2021/12/19 20:08:37 dns: OScfg: {Nameservers:[] SearchDomains:[] MatchDomains:[]}
> 2021/12/19 20:08:37 logtail: dialed "log.tailscale.io:443" in 223ms
> jq: error (at <stdin>:1): Cannot iterate over null (null)
> false
> false
> false
> false
> false
> false
> false

## Steps to reproduce

Running Home Assistant Supervised on Orange Pi with Armbian 21.08.01. Everything else working, plus have run Tailscale outside HA (not in container) on it before.

## Proposed changes

?

**Comment by frenck** [comment]
This is kinda expected behavior, from the logs at least.
Please note, that Armbian is not supported by Home Assistant.

**Comment by bohtho** [comment]
I know Armbian isn't supported but it seems to work for others. Also the few software pieces I'm going to run on it has been run on it previously (although run differently).

This is for both Safari and Firefox on a Mac OS 12.1.

But, could this be a freak accident...? Tailscale.com is loading fine but login.tailscale.com directly won't in neither...

**Comment by frenck** [comment]
Expected actually. Try Chrome.

**Comment by bohtho** [comment]
Kicked in on Firefox after some retries. I disabled some security settings for the site but don't know if that was it.

Added itself to my Tailscale network. Amazing work integrating it into HA on an Orange Pi Zero like that! Thanks. Sorry about that, this can be closed.

**Comment by frenck** [comment]
> Kicked in on Firefox after some retries. I disabled some security settings for the site but don't know if that was it.

Yeah, there is a known bug in Firefox that can cause this. (should have been fixed in the latest Firefox 95.1 I think... not a Firefox user myself, just repeating messages of others now).

Anyways, Great you got it going 👍
