### ISSUE TITLE
Outbound access

### ISSUE THREAD

**Issue by pittbull** [hassio-addons/addon-tailscale#67]
# Problem/Motivation

Access to Glances running on a node in my Tailscale network

## Expected behavior

After installing the addon I expected HA to connect to this host successfully

## Actual behavior

Unable to access the host. HA shows in the TS admin and other Tailscale hosts can ping and access HA - I am not able though to access anything from HA.

I am not sure if this is supposed to work but I am unable to conclude based on the information I find.

**Comment by robroll** [comment]
I am looking for a solution to this too.

My HA is on 192.168.5.x in one location. In another location I have a camera on 192.168.1.x connected to my Tailscale via an openwrt router. My laptop is able to access both. The HA (192.168.5.x) is unable to see the camera (I have created a ping sesnsor in the configuration file to test).

**Comment by apmillen** [comment]
I am also looking for something like this. I think tailscale would have to be installed on the OS rather than in a docker container so I'm not sure this will ever work.

**Comment by pittbull** [comment]
Any feedback on this?

**Comment by JordiMD92** [comment]
Having the same issue.
I have 3 Home assistants with Tailscale client on each. I would like to be able to access from the main one to the secondary one with remote home assistant to have the information centralized.

Currently using wireguard but i want get rid of it.

**Comment by frenck** [comment]
Currently, this add-on is accessing just Home Assistant itself. Due to its containerized nature and the way it is set up, it can currently not be used for routing Home Assistant itself out.

I'll make a task to update to documentation to make that more clear.
