### ISSUE TITLE
Magic DNS, HA & AdGuard/Pi-Hole

### ISSUE THREAD

**Issue by publicarray** [hassio-addons/addon-tailscale#74]
According to https://tailscale.com/kb/1114/pi-hole/

> When running tailscale up, you’ll need to pass the `--accept-dns=false` flag. Pi-Hole uses DNS servers configured within Linux as its upstream servers, where it will send DNS queries that it cannot answer on its own. Since we’re going to make the Pi-Hole be our DNS server, we don’t want Pi-Hole trying to use itself as its own upstream.

It would be nice to disable DNS as an option: `--accept-dns=false` so we can use HA - AdGuard as the DNS server for all tailscale nodes.

https://github.com/hassio-addons/addon-tailscale/blob/cb67a29a25c4dc71648ef01b29b806e25a6a2351/tailscale/rootfs/etc/services.d/tailscaled/post#L53-L59

**Comment by stroodle96** [comment]
I second this request. Is much needed. Thanks!

**Comment by AiR-0nE** [comment]
I also try to do this, please help 🙂 !

**Comment by Grunt-Futtocks** [comment]
This is what worked for me and seems to be working ok so far, someone will probably say this is a bad idea but I'll stick with it until then.
Point Homeassistant IP as NameServer in Tailscale Admin, check the override dns on the right.
Head over to Homeassistant addons-backups-system click system and change on the ip address settings.
Enter 172.30.32.1 as the dns server and save (same ip used with the wireguard addon for adguard).

**Comment by Grunt-Futtocks** [comment]
Forgot to mention subnets, enable that in Tailscale admin for Homeassistant machine.
No need for 'accept-dns=false'

Also to clarify,  Homeassistant IP for TS admin DNS is your local home LAN IP.

**Comment by publicarray** [comment]
Yea that doesn't work for me. I've tried that already.
