### ISSUE TITLE
Failed to log in: null is not an object (evaluating 'window.open(url, "_blank").focus')

### ISSUE THREAD

**Issue by AnKloss** [hassio-addons/addon-tailscale#79]
New installation
Add-on version: 0.5.3
 You are running the latest version of this add-on.
 System: Home Assistant OS 7.4  (aarch64 / raspberrypi4-64)
 Home Assistant Core: 2022.2.9
 Home Assistant Supervisor: 2022.01.1
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] nginx.sh: executing... 
[cont-init.d] nginx.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[15:53:52] INFO: Starting Tailscale web...
[15:53:52] INFO: Starting Tailscale...
2022/02/27 15:53:52 web server running on: http://127.0.0.1:25899
[15:53:52] INFO: Starting NGinx...
2022/02/27 15:53:52 logtail started
2022/02/27 15:53:52 Program starting: v1.20.4-t8c6cb1cea-g2accf24a5, Go 1.17.6-tse44d304e54: []string{"/opt/tailscaled", "--state=/data/tailscaled.state", "--tun=userspace-networking"}
2022/02/27 15:53:52 LogID: acbb6683d1e9fcf417f5113c15a2..............xxxxxxxxxxxxxxxx
2022/02/27 15:53:52 logpolicy: using system state directory "/var/lib/tailscale"
logpolicy.Read /var/lib/tailscale/tailscaled.log.conf: open /var/lib/tailscale/tailscaled.log.conf: no such file or directory
2022/02/27 15:53:52 wgengine.NewUserspaceEngine(tun "userspace-networking") ...
2022/02/27 15:53:52 dns: using dns.noopManager
2022/02/27 15:53:52 link state: interfaces.State{defaultRoute=eth0 ifs={docker0:[172.17.0.1/16] eth0:[192.168.222.106/24] hassio:[172.30.32.1/23]} v4=true v6=false}
2022/02/27 15:53:52 magicsock: disco key = d:9c6ffabca1.....xxxxxxxxx
2022/02/27 15:53:52 Creating wireguard device...
2022/02/27 15:53:52 Bringing wireguard device up...
2022/02/27 15:53:52 Bringing router up...
2022/02/27 15:53:52 Clearing router settings...
2022/02/27 15:53:52 Starting link monitor...
2022/02/27 15:53:52 Engine created.
2022/02/27 15:53:52 netmap packet filter: (not ready yet)
2022/02/27 15:53:52 Start
2022/02/27 15:53:52 using backend prefs
2022/02/27 15:53:52 backend prefs for "_daemon": Prefs{ra=true dns=true want=false routes=[] nf=on Persist=nil}
2022/02/27 15:53:52 got initial portlist info in 0s
2022/02/27 15:53:52 control: HostInfo: {"IPNVersion":"1.20.4-t8c6cb1cea-g2accf24a5","BackendLogID":"acbb6683d1e9fcf417f5113c15a22f49fe92c4cb......xxxxxxxxxxxxxxx","OS":"linux","OSVersion":"Alpine Linux v3.15; kernel=5.10.92-v8; container","Hostname":"a0d7b954-tailscale","GoArch":"arm64","Services":[{"Proto":"tcp","Port":139},{"Proto":"tcp","Port":445},{"Proto":"tcp","Port":1883},{"Proto":"tcp","Port":1884},{"Proto":"tcp","Port":4357},{"Proto":"tcp","Port":5355},{"Proto":"tcp","Port":8123},{"Proto":"tcp","Port":8485},{"Proto":"tcp","Port":8883},{"Proto":"tcp","Port":8884},{"Proto":"tcp","Port":38997},{"Proto":"tcp","Port":62066,"Description":"nginx: worker process"}]}
2022/02/27 15:53:52 control: authRoutine: state:new; goal=nil paused=false
2022/02/27 15:53:52 control: mapRoutine: state:new
2022/02/27 15:53:52 Backend: logs: be:acbb6683d1e9fcf417f5113c15a22f49fe92c4cbd.......xxxxxxxxxxxxxxxxxxxx fe:
2022/02/27 15:53:52 Switching ipn state NoState -> NeedsLogin (WantRunning=false, nm=false)
2022/02/27 15:53:52 blockEngineUpdates(true)
2022/02/27 15:53:52 health("overall"): error: state=NeedsLogin, wantRunning=false
2022/02/27 15:53:52 wgengine: Reconfig: configuring userspace wireguard config (with 0/0 peers)
2022/02/27 15:53:52 wgengine: Reconfig: configuring router
2022/02/27 15:53:52 wgengine: Reconfig: configuring DNS
2022/02/27 15:53:52 dns: Set: {DefaultResolvers:[] Routes:{} SearchDomains:[] Hosts:0}
2022/02/27 15:53:52 dns: Resolvercfg: {Routes:{} Hosts:0 LocalDomains:[]}
2022/02/27 15:53:52 dns: OScfg: {Nameservers:[] SearchDomains:[] MatchDomains:[]}
2022/02/27 15:53:53 logtail: dialed "log.tailscale.io:443" in 276ms
jq: error (at <stdin>:1): Cannot iterate over null (null)
false
false
false
false
and so on....... fales..

In login I get this>>>
Failed to log in: null is not an object (evaluating 'window.open(url, "_blank").focus')

Please note I have cut out login ID with .........xxxxxxxxxxxx
Can you help, how to fix this ??? 

mfg
Andreas

**Comment by AnKloss** [comment]
update to 0.54

same error

2022/03/01 02:09:19 Switching ipn state NoState -> NeedsLogin (WantRunning=false, nm=false)
2022/03/01 02:09:19 blockEngineUpdates(true)
2022/03/01 02:09:19 health("overall"): error: state=NeedsLogin, wantRunning=false
2022/03/01 02:09:19 wgengine: Reconfig: configuring userspace wireguard config (with 0/0 peers)
2022/03/01 02:09:19 wgengine: Reconfig: configuring router
2022/03/01 02:09:19 wgengine: Reconfig: configuring DNS
2022/03/01 02:09:19 dns: Set: {DefaultResolvers:[] Routes:{} SearchDomains:[] Hosts:0}
2022/03/01 02:09:19 dns: Resolvercfg: {Routes:{} Hosts:0 LocalDomains:[]}
2022/03/01 02:09:19 dns: OScfg: {Nameservers:[] SearchDomains:[] MatchDomains:[]}
[02:09:19] INFO: Starting NGinx...
jq: error (at <stdin>:1): Cannot iterate over null (null)
false
false
false
false

**Comment by frenck** [comment]
fixed in https://github.com/hassio-addons/addon-tailscale/pull/81
