### ISSUE TITLE
Don't advertise address family if forwarding for that family is disabled

### ISSUE THREAD

**Issue by frenck** [hassio-addons/addon-tailscale#8]
# Problem/Motivation

This happens on e.g., Home Assistant OS, which doesn't have forwarding for IPv6 enabled,
causing:

`Warning: net.ipv6.conf.all.forwarding is disabled. Subnet routes won't work.`

It would be better if the add-on would check if it was enabled or not, before advertising those networks. Advertising IPv6 networks in that case, can be skipped.

**Comment by Mincka** [comment]
Without IP forwarding enabled for both IPv4 **and** IPv6 at OS level, the user will also see this warning message in Tailscale interface:
![image](https://user-images.githubusercontent.com/6184289/130213159-8f854aec-a909-482f-9877-19c529688bdc.png)

I can confirm that temporarily enabling port forwarding on HA OS will make the warning in the log and in the web GUI goes away.
For anything interested to test:
https://developers.home-assistant.io/docs/operating-system/debugging
`sysctl -w net.ipv6.conf.all.forwarding=1`

However, the routing does not work for me. Creating a dedicated thread for this.

**Comment by frenck** [comment]
fixed in #19
routes that can't be forwarded, won't be advertised
