### ISSUE TITLE
Failed to login

### ISSUE THREAD

**Issue by tarbax** [hassio-addons/addon-tailscale#86]
I always get this error when trying to log in:

in home network and via 4g (ingress)

![446DFCF9-B7BF-4B9B-AAAD-412709B1C25E](https://user-images.githubusercontent.com/34491557/158762998-48c5ca71-1009-4513-9b98-4aec2c0cd7e9.png)

**Comment by lukasleitsch** [comment]
I had the same issue with opening the link on an iOS-Device.

You have to use the Chrome Browser on a desktop to open the Link.

> Open the Web UI of the "Tailscale" add-on to complete authentication and couple your Home Assistant instance with your Tailscale account. Note: Some browsers don't work with this step. It is recommended to complete this step on a desktop or laptop computer using the Chrome browser.

Step 5 of the installation section: https://github.com/hassio-addons/addon-tailscale/blob/main/tailscale/DOCS.md#installation
