### ISSUE TITLE
allow change of tailscale url

### ISSUE THREAD

**Issue by scharc** [hassio-addons/addon-tailscale#90]
# Problem/Motivation

I am running a self hosted version of tailscale called headscale on my private server. It is currently not possible to change the login-url

See https://github.com/juanfont/headscale

## Expected behavior

Config flag for custom login url

## Actual behavior

No flags 

## Steps to reproduce

Installed plugin uses hard coded url

## Proposed changes

Make custom form to add flag '--login-url URL'

**Comment by frenck** [comment]
> It is currently not possible to change the login-url

That is correct and not a bug? 🤷

**Comment by scharc** [comment]
It is not a bug more like a add-on for the add-on to make it so that people could use there own tailscale server and point the add-on to this server. 

I can provide a custom test instance if needed for testing.

**Comment by frenck** [comment]
I have no personal interest in adding such a thing 🤷

**Comment by scharc** [comment]
Any clues how to add a custom option / parameter to the run or post script how to add the extra flag? It is just adding one more parameter to the tailscaled call

**Comment by frenck** [comment]
> It is just adding one more parameter to the tailscaled call

All options are "just one more parameter"; in the end it ends up with all parameters and lots of complexity. If you are in need for these options, I suggest not to use this add-on 👍
