### ISSUE TITLE
not able to route to exit node

### ISSUE THREAD

**Issue by alamoudimoh** [hassio-addons/addon-tailscale#97]
# Problem/Motivation

i am trying to make Home Assistant route traffic to my exit node, but cannot find where or how

## Expected behavior
ability to add the route to specific exit node

**Comment by finnoprey** [comment]
Frenck has stated that this is **isn't possible** in a similar issue: https://github.com/hassio-addons/addon-tailscale/issues/67#issuecomment-1075538349
